package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;

import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Fetches the authenticated user's currently assigned WhatsApp username,
 * together with its verification state and recovery PIN hash.
 *
 * <p>Usernames are an alternative identifier to phone numbers introduced as
 * part of WhatsApp's privacy roadmap. This query returns the username
 * associated with the caller's account, the state of the registration
 * (pending, active, etc.) and the PIN hash used for recovery.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexGetUsernameJob.mexGetUsernameQueryJob: sends
 * {@code WAWebMexGetUsernameJobQuery} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexGetUsernameJob")
@WhatsAppWebModule(moduleName = "WAWebMexGetUsernameJobQuery.graphql")
public sealed interface GetUsernameMex extends MexJsonOperation permits GetUsernameMex.Request, GetUsernameMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexGetUsernameJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexGetUsernameJobQuery.graphql: corresponds to the
     * {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexGetUsernameJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "25347099718279209";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements GetUsernameMex {

        public Request() {
        }

        /**
         * Serialises an empty GraphQL variables envelope and wraps it in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexGetUsernameJob.mexGetUsernameQueryJob: the query
         * takes no variables and returns the username bound to the caller.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetUsernameJob", exports = "mexGetUsernameQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements GetUsernameMex {
        private final UsernameInfo usernameInfo;

        private Response(UsernameInfo usernameInfo) {
            this.usernameInfo = usernameInfo;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexGetUsernameJob.mexGetUsernameQueryJob: reads the
         * {@code username_info} record with {@code username}, {@code state}
         * and {@code pin}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetUsernameJob", exports = "mexGetUsernameQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code username_info} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<UsernameInfo> usernameInfo() {
            return Optional.ofNullable(usernameInfo);
        }

        /**
         * A parsed {@code UsernameInfo} object.
         */
        public static final class UsernameInfo {
            private final String username;
            private final String state;
            private final String pin;

            private UsernameInfo(String username, String state, String pin) {
                this.username = username;
                this.state = state;
                this.pin = pin;
            }

            /**
             * Returns the {@code username} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> username() {
                return Optional.ofNullable(username);
            }

            /**
             * Returns the {@code state} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> state() {
                return Optional.ofNullable(state);
            }

            /**
             * Returns the {@code pin} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> pin() {
                return Optional.ofNullable(pin);
            }

            /**
             * Parses a {@code UsernameInfo} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<UsernameInfo> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var username = obj.getString("username");
                var state = obj.getString("state");
                var pin = obj.getString("pin");
                return Optional.of(new UsernameInfo(username, state, pin));
            }

            /**
             * Parses a list of {@code UsernameInfo} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<UsernameInfo> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<UsernameInfo>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_get");
            if (root == null) {
                return Optional.empty();
            }

            var usernameInfo = UsernameInfo.of(root.getJSONObject("username_info")).orElse(null);

            return Optional.of(new Response(usernameInfo));
        }
    }
}
