package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Claims or updates the authenticated user's WhatsApp username, optionally
 * reserving it during a sign-up session.
 *
 * <p>The mutation accepts the requested username together with a
 * {@code reserved} flag (used to pre-claim a username during onboarding
 * without finalising it), a {@code session_id} tying the reservation to a
 * specific registration flow and a {@code source} tag identifying the entry
 * point. The response echoes a status token that drives the post-submit UI
 * state.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexSetUsernameJob.mexSetUsernameQueryJob: sends
 * {@code WAWebMexSetUsernameJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexSetUsernameJob")
@WhatsAppWebModule(moduleName = "WAWebMexSetUsernameJobMutation.graphql")
public sealed interface SetUsernameMex extends MexJsonOperation permits SetUsernameMex.Request, SetUsernameMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexSetUsernameJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexSetUsernameJobMutation.graphql: corresponds to the
     * {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "25757341163897635";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements SetUsernameMex {
        private final String input;
        private final Boolean reserved;
        private final String sessionId;
        private final String source;

        public Request(String input, Boolean reserved, String sessionId, String source) {
            this.input = input;
            this.reserved = reserved;
            this.sessionId = sessionId;
            this.source = source;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexSetUsernameJob.mexSetUsernameQueryJob: the
         * variables {@code input}, {@code reserved}, {@code session_id} and
         * {@code source} mirror the WA Web call signature.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameJob", exports = "mexSetUsernameQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                if (reserved != null) {
                    writer.writeName("reserved");
                    writer.writeColon();
                    writer.writeBool(reserved);
                }
                if (sessionId != null) {
                    writer.writeName("session_id");
                    writer.writeColon();
                    writer.writeString(sessionId);
                }
                if (source != null) {
                    writer.writeName("source");
                    writer.writeColon();
                    writer.writeString(source);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements SetUsernameMex {
        private final String result;

        private Response(String result) {
            this.result = result;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexSetUsernameJob.mexSetUsernameQueryJob: reads the
         * {@code result} status token from the mutation payload.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameJob", exports = "mexSetUsernameQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code result} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_set");
            if (root == null) {
                return Optional.empty();
            }

            var result = root.getString("result");

            return Optional.of(new Response(result));
        }
    }
}
