package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Claims or updates the authenticated user's WhatsApp username, optionally
 * reserving it during a sign-up session.
 *
 * <p>The mutation accepts the requested username together with a
 * {@code reserved} flag (used to pre-claim a username during onboarding
 * without finalising it), a {@code session_id} tying the reservation to a
 * specific registration flow and a {@code source} tag identifying the entry
 * point. The response echoes a status token that drives the post-submit UI
 * state.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexSetUsernameJob.mexSetUsernameQueryJob: sends
 * {@code WAWebMexSetUsernameJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
public final class SetUsernameMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexSetUsernameJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexSetUsernameJobMutation.graphql: corresponds to the
     * {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "25757341163897635";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexSetUsernameQueryJob
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexSetUsernameJobMutation.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexSetUsernameQueryJob"}.
     */
    public static final String OPERATION_NAME = "mexSetUsernameQueryJob";
    private final String input;
    private final Boolean reserved;
    private final String sessionId;
    private final String source;

    public SetUsernameMexRequest(String input, Boolean reserved, String sessionId, String source) {
        this.input = input;
        this.reserved = reserved;
        this.sessionId = sessionId;
        this.source = source;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexSetUsernameJobMutation.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexSetUsernameJobMutation.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * <p>Mirrors the WA Web {@code isStringNullOrEmpty(t.input) ? {} : t}
     * gate: when {@code input} is {@code null} or empty, the variables
     * object is emitted as {@code {}} regardless of the other fields. When
     * {@code input} is present, all four variables ({@code input},
     * {@code reserved}, {@code session_id}, {@code source}) are forwarded
     * verbatim so the GraphQL relay receives the full payload {@code t}.
     *
     * @implNote WAWebMexSetUsernameJob.mexSetUsernameQueryJob: invokes
     * {@code WAWebMexClient.fetchQuery(mutation,
     * isStringNullOrEmpty(t.input) ? {} : t)}. Cobalt reproduces the same
     * conditional, omitting the entire variables payload when the input
     * username is missing.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameJob", exports = "mexSetUsernameQueryJob",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            // WAWebMexSetUsernameJob.mexSetUsernameQueryJob: isStringNullOrEmpty(t.input) ? {} : t
            if (input != null && !input.isEmpty()) {
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
                if (reserved != null) {
                    writer.writeName("reserved");
                    writer.writeColon();
                    writer.writeBool(reserved);
                }
                if (sessionId != null) {
                    writer.writeName("session_id");
                    writer.writeColon();
                    writer.writeString(sessionId);
                }
                if (source != null) {
                    writer.writeName("source");
                    writer.writeColon();
                    writer.writeString(source);
                }
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
