package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Sets or rotates the recovery PIN associated with the user's WhatsApp
 * username.
 *
 * <p>The username PIN is the secret that allows account recovery when the
 * primary phone number is unavailable. This mutation registers a new PIN
 * (or updates the existing one) after the user completes the "Account
 * {@literal ->} Username PIN" flow in settings.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexSetUsernameKeyJob.mexSetUsernameKeyQueryJob: sends
 * {@code WAWebMexSetUsernameKeyJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexSetUsernameKeyJob")
@WhatsAppWebModule(moduleName = "WAWebMexSetUsernameKeyJobMutation.graphql")
public sealed interface SetUsernameKeyMex extends MexJsonOperation permits SetUsernameKeyMex.Request, SetUsernameKeyMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexSetUsernameKeyJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexSetUsernameKeyJobMutation.graphql: corresponds to
     * the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameKeyJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9749436995157074";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements SetUsernameKeyMex {
        private final String pin;

        public Request(String pin) {
            this.pin = pin;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexSetUsernameKeyJob.mexSetUsernameKeyQueryJob: the
         * single {@code pin} variable carries the new recovery PIN.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameKeyJob", exports = "mexSetUsernameKeyQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (pin != null) {
                    writer.writeName("pin");
                    writer.writeColon();
                    writer.writeString(pin);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements SetUsernameKeyMex {
        private final String result;

        private Response(String result) {
            this.result = result;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexSetUsernameKeyJob.mexSetUsernameKeyQueryJob:
         * reads the {@code result} status from
         * {@code data.xwa2_username_pin_set}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexSetUsernameKeyJob", exports = "mexSetUsernameKeyQueryJob",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code result} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_username_pin_set");
            if (root == null) {
                return Optional.empty();
            }

            var result = root.getString("result");

            return Optional.of(new Response(result));
        }
    }
}
