package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Publishes or clears the authenticated user's ephemeral text status entry.
 *
 * <p>The mutation takes the serialised status payload (text body, optional
 * emoji and ephemeral duration) and commits it as the current status for
 * the account. Setting an empty input clears any existing status.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexUpdateTextStatusJob.mexUpdateTextStatus: sends
 * {@code WAWebMexUpdateTextStatusJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexUpdateTextStatusJob")
@WhatsAppWebModule(moduleName = "WAWebMexUpdateTextStatusJobMutation.graphql")
public sealed interface UpdateTextStatusMex extends MexJsonOperation permits UpdateTextStatusMex.Request, UpdateTextStatusMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexUpdateTextStatusJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexUpdateTextStatusJobMutation.graphql: corresponds to
     * the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateTextStatusJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9152604461510864";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements UpdateTextStatusMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexUpdateTextStatusJob.mexUpdateTextStatus: the
         * single {@code input} variable carries the serialised status
         * payload.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUpdateTextStatusJob", exports = "mexUpdateTextStatus",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements UpdateTextStatusMex {
        private final String result;

        private Response(String result) {
            this.result = result;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexUpdateTextStatusJob.mexUpdateTextStatus: reads
         * the {@code result} status from
         * {@code data.xwa2_update_text_status}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUpdateTextStatusJob", exports = "mexUpdateTextStatus",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code result} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> result() {
            return Optional.ofNullable(result);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_update_text_status");
            if (root == null) {
                return Optional.empty();
            }

            var result = root.getString("result");

            return Optional.of(new Response(result));
        }
    }
}
