package com.github.auties00.cobalt.node.mex.json.user;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Publishes or clears the authenticated user's ephemeral text status entry.
 *
 * <p>The mutation takes the serialised status payload (text body, optional
 * emoji and ephemeral duration) and commits it as the current status for
 * the account. Setting an empty input clears any existing status.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexUpdateTextStatusJob.mexUpdateTextStatus: sends
 * {@code WAWebMexUpdateTextStatusJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
public final class UpdateTextStatusMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexUpdateTextStatusJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexUpdateTextStatusJobMutation.graphql: corresponds to
     * the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateTextStatusJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "9152604461510864";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexUpdateTextStatus
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexUpdateTextStatusJobMutation.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexUpdateTextStatus"}.
     */
    public static final String OPERATION_NAME = "mexUpdateTextStatus";
    private final String text;
    private final String emoji;
    private final long ephemeralDurationSec;

    /**
     * Constructs a new request with the three status components.
     *
     * @implNote WAWebTextStatusParseUtils.createTextStatusObjectForUpdateRequest:
     * applies the same normalisation as the WA Web helper:
     * <ul>
     *   <li>An empty {@code text} string is coerced to {@code null}.</li>
     *   <li>A {@code null} {@code emoji} is omitted from the
     *       {@code emoji} object entirely.</li>
     *   <li>If both {@code text} and {@code emoji} are absent and the
     *       caller supplied a non-zero ephemeral duration, the duration
     *       is silently reset to {@code 0}.</li>
     * </ul>
     *
     * @param text the text body of the status, or {@code null} / empty
     *             to clear it
     * @param emoji the optional emoji decoration of the status, or
     *              {@code null} to omit
     * @param ephemeralDurationSec the ephemeral duration in seconds, or
     *                             {@code 0} for no expiry
     */
    public UpdateTextStatusMexRequest(String text, String emoji, long ephemeralDurationSec) {
        this.text = text;
        this.emoji = emoji;
        this.ephemeralDurationSec = ephemeralDurationSec;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexUpdateTextStatusJobMutation.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexUpdateTextStatusJobMutation.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @implNote WAWebMexUpdateTextStatusJob.mexUpdateTextStatus: the
     * single {@code input} variable carries the structured status
     * payload built by
     * {@code WAWebTextStatusParseUtils.createTextStatusObjectForUpdateRequest}
     * with shape {@code {text, emoji?: {content}, ephemeral_duration_sec}}.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateTextStatusJob", exports = "mexUpdateTextStatus",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        // WAWebTextStatusParseUtils.createTextStatusObjectForUpdateRequest:
        // n = textStatusString === "" ? null : textStatusString
        var normalisedText = (text == null || text.isEmpty()) ? null : text;
        // r = textStatusEphemeralDuration ?? 0
        // if (n == null && textStatusEmoji == null && r !== 0) r = 0
        var normalisedDuration = ephemeralDurationSec;
        if (normalisedText == null && emoji == null && normalisedDuration != 0L) {
            normalisedDuration = 0L;
        }
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            writer.writeName("input");
            writer.writeColon();
            writer.startObject();
            // WAWebTextStatusParseUtils: {text: n, ...}
            writer.writeName("text");
            writer.writeColon();
            if (normalisedText == null) {
                writer.writeNull();
            } else {
                writer.writeString(normalisedText);
            }
            // WAWebTextStatusParseUtils: emoji object is only set when
            // textStatusEmoji != null - otherwise the property is omitted
            if (emoji != null) {
                writer.writeName("emoji");
                writer.writeColon();
                writer.startObject();
                writer.writeName("content");
                writer.writeColon();
                writer.writeString(emoji);
                writer.endObject();
            }
            // WAWebTextStatusParseUtils: ephemeral_duration_sec is always set
            writer.writeName("ephemeral_duration_sec");
            writer.writeColon();
            writer.writeInt64(normalisedDuration);
            writer.endObject();
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
