// Generated by jextract

package com.github.auties00.cobalt.calls2.net.bwe;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class ExecuTorch extends ExecuTorch$shared {

    ExecuTorch() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int COBALT_ET_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_ET_OK 0
     * }
     */
    public static int COBALT_ET_OK() {
        return COBALT_ET_OK;
    }

    private static class ml_shim_create_executorch {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            ExecuTorch.C_POINTER,
            ExecuTorch.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ml_shim_create_executorch");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void *ml_shim_create_executorch(const char *model_path)
     * }
     */
    public static FunctionDescriptor ml_shim_create_executorch$descriptor() {
        return ml_shim_create_executorch.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void *ml_shim_create_executorch(const char *model_path)
     * }
     */
    public static MethodHandle ml_shim_create_executorch$handle() {
        return ml_shim_create_executorch.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void *ml_shim_create_executorch(const char *model_path)
     * }
     */
    public static MemorySegment ml_shim_create_executorch$address() {
        return ml_shim_create_executorch.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void *ml_shim_create_executorch(const char *model_path)
     * }
     */
    public static MemorySegment ml_shim_create_executorch(MemorySegment model_path) {
        var mh$ = ml_shim_create_executorch.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ml_shim_create_executorch", model_path);
            }
            return (MemorySegment)mh$.invokeExact(model_path);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ml_shim_forward {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            ExecuTorch.C_INT,
            ExecuTorch.C_POINTER,
            ExecuTorch.C_POINTER,
            ExecuTorch.C_INT,
            ExecuTorch.C_POINTER,
            ExecuTorch.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ml_shim_forward");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t ml_shim_forward(void *model, const float *input, int32_t input_len, float *output, int32_t output_capacity)
     * }
     */
    public static FunctionDescriptor ml_shim_forward$descriptor() {
        return ml_shim_forward.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t ml_shim_forward(void *model, const float *input, int32_t input_len, float *output, int32_t output_capacity)
     * }
     */
    public static MethodHandle ml_shim_forward$handle() {
        return ml_shim_forward.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t ml_shim_forward(void *model, const float *input, int32_t input_len, float *output, int32_t output_capacity)
     * }
     */
    public static MemorySegment ml_shim_forward$address() {
        return ml_shim_forward.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t ml_shim_forward(void *model, const float *input, int32_t input_len, float *output, int32_t output_capacity)
     * }
     */
    public static int ml_shim_forward(MemorySegment model, MemorySegment input, int input_len, MemorySegment output, int output_capacity) {
        var mh$ = ml_shim_forward.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ml_shim_forward", model, input, input_len, output, output_capacity);
            }
            return (int)mh$.invokeExact(model, input, input_len, output, output_capacity);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ml_shim_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            ExecuTorch.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ml_shim_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void ml_shim_free(void *model)
     * }
     */
    public static FunctionDescriptor ml_shim_free$descriptor() {
        return ml_shim_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void ml_shim_free(void *model)
     * }
     */
    public static MethodHandle ml_shim_free$handle() {
        return ml_shim_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void ml_shim_free(void *model)
     * }
     */
    public static MemorySegment ml_shim_free$address() {
        return ml_shim_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void ml_shim_free(void *model)
     * }
     */
    public static void ml_shim_free(MemorySegment model) {
        var mh$ = ml_shim_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ml_shim_free", model);
            }
            mh$.invokeExact(model);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ml_get_shim_create_status {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            ExecuTorch.C_INT    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("ml_get_shim_create_status");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t ml_get_shim_create_status()
     * }
     */
    public static FunctionDescriptor ml_get_shim_create_status$descriptor() {
        return ml_get_shim_create_status.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t ml_get_shim_create_status()
     * }
     */
    public static MethodHandle ml_get_shim_create_status$handle() {
        return ml_get_shim_create_status.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t ml_get_shim_create_status()
     * }
     */
    public static MemorySegment ml_get_shim_create_status$address() {
        return ml_get_shim_create_status.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t ml_get_shim_create_status()
     * }
     */
    public static int ml_get_shim_create_status() {
        var mh$ = ml_get_shim_create_status.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ml_get_shim_create_status");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int COBALT_ET_ERR_OPEN = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_ET_ERR_OPEN -1
     * }
     */
    public static int COBALT_ET_ERR_OPEN() {
        return COBALT_ET_ERR_OPEN;
    }
    private static final int COBALT_ET_ERR_LOAD = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_ET_ERR_LOAD -2
     * }
     */
    public static int COBALT_ET_ERR_LOAD() {
        return COBALT_ET_ERR_LOAD;
    }
    private static final int COBALT_ET_ERR_BACKEND = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_ET_ERR_BACKEND -3
     * }
     */
    public static int COBALT_ET_ERR_BACKEND() {
        return COBALT_ET_ERR_BACKEND;
    }
    private static final int COBALT_ET_ERR_RUNTIME = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define COBALT_ET_ERR_RUNTIME -4
     * }
     */
    public static int COBALT_ET_ERR_RUNTIME() {
        return COBALT_ET_ERR_RUNTIME;
    }
}

