package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Fetches the invite code currently associated with a group, used to build
 * the shareable {@code chat.whatsapp.com/<code>} link.
 *
 * <p>The invite code is the opaque string the server generates when a group
 * is created and rotates whenever an admin issues a new code. This query
 * returns the current value without regenerating it; to rotate the code a
 * dedicated "create invite code" MEX mutation must be used.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchGroupInviteCodeJobQuery.graphql: the compiled
 * GraphQL operation is dispatched through {@code WAWebMexClient.fetchQuery}
 * and returns the {@code invite_code} field of {@code xwa2_group_query_by_id}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchGroupInviteCodeJobQuery.graphql")
public sealed interface FetchGroupInviteCodeMex extends MexJsonOperation permits FetchGroupInviteCodeMex.Request, FetchGroupInviteCodeMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchGroupInviteCodeJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchGroupInviteCodeJobQuery.graphql: corresponds to
     * the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInviteCodeJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "29247029834912157";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchGroupInviteCodeMex {
        private final String id;
        private final String queryContext;

        public Request(String id, String queryContext) {
            this.id = id;
            this.queryContext = queryContext;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchGroupInviteCodeJobQuery.graphql: the two
         * variables are the group {@code id} and the {@code query_context}
         * tag.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInviteCodeJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (id != null) {
                    writer.writeName("id");
                    writer.writeColon();
                    writer.writeString(id);
                }
                if (queryContext != null) {
                    writer.writeName("query_context");
                    writer.writeColon();
                    writer.writeString(queryContext);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchGroupInviteCodeMex {
        private final String inviteCode;
        private final String id;

        private Response(String inviteCode, String id) {
            this.inviteCode = inviteCode;
            this.id = id;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchGroupInviteCodeJobQuery.graphql: reads
         * {@code data.xwa2_group_query_by_id.invite_code} and the group
         * {@code id}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInviteCodeJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code invite_code} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> inviteCode() {
            return Optional.ofNullable(inviteCode);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_query_by_id");
            if (root == null) {
                return Optional.empty();
            }

            var inviteCode = root.getString("invite_code");
            var id = root.getString("id");

            return Optional.of(new Response(inviteCode, id));
        }
    }
}
