package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;

/**
 * Fetches full metadata for a group, including creator, subject, description,
 * human participants (bots excluded), group state and all configurable
 * properties.
 *
 * <p>This is the standard group info query issued when opening a chat or
 * refreshing group metadata on demand. The response carries the full group
 * profile: creator identity (jid, lid, pn, username), subject with last edit
 * timestamp, description with last edit timestamp, participant edges with
 * roles, ephemeral timer, membership approval settings, LID migration state,
 * parent community link and group lock status.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchGroupInfoJob.mexGetGroupInfo: sends
 * {@code WAWebMexFetchGroupInfoJobQuery} through
 * {@code WAWebMexClient.fetchQuery} and reads the full
 * {@code xwa2_group_query_by_id} envelope.
 */
public final class FetchGroupInfoMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchGroupInfoJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchGroupInfoJobQuery.graphql: corresponds to the
     * {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInfoJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "26197094166585473";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexGetGroupInfo
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexFetchGroupInfoJobQuery.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexGetGroupInfo"}.
     */
    public static final String OPERATION_NAME = "mexGetGroupInfo";
    private final String id;
    private final Boolean includeUsername;
    private final String participantsPhash;
    private final String queryContext;

    public FetchGroupInfoMexRequest(String id, Boolean includeUsername, String participantsPhash, String queryContext) {
        this.id = id;
        this.includeUsername = includeUsername;
        this.participantsPhash = participantsPhash;
        this.queryContext = queryContext;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexFetchGroupInfoJobQuery.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexFetchGroupInfoJobQuery.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @implNote WAWebMexFetchGroupInfoJob.mexGetGroupInfo: variables
     * are {@code id}, {@code include_username}, {@code participants_phash}
     * and {@code query_context}; the underlying
     * {@code WAWebMexFetchGroupInfoJob._/fetchGetGroupInfo} helper does
     * the actual {@code WAWebMexClient.fetchQuery} dispatch.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchGroupInfoJob", exports = "mexGetGroupInfo",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            if (id != null) {
                writer.writeName("id");
                writer.writeColon();
                writer.writeString(id);
            }
            if (includeUsername != null) {
                writer.writeName("include_username");
                writer.writeColon();
                writer.writeBool(includeUsername);
            }
            if (participantsPhash != null) {
                writer.writeName("participants_phash");
                writer.writeColon();
                writer.writeString(participantsPhash);
            }
            if (queryContext != null) {
                writer.writeName("query_context");
                writer.writeColon();
                writer.writeString(queryContext);
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
