package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchGroupInviteCode} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchGroupInviteCodeMex extends MexJsonOperation permits FetchGroupInviteCodeMex.Request, FetchGroupInviteCodeMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "29247029834912157";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchGroupInviteCodeMex {
        private final String id;
        private final String queryContext;

        public Request(String id, String queryContext) {
            this.id = id;
            this.queryContext = queryContext;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (id != null) {
                    writer.writeName("id");
                    writer.writeColon();
                    writer.writeString(id);
                }
                if (queryContext != null) {
                    writer.writeName("query_context");
                    writer.writeColon();
                    writer.writeString(queryContext);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchGroupInviteCodeMex {
        private final String inviteCode;
        private final String id;

        private Response(String inviteCode, String id) {
            this.inviteCode = inviteCode;
            this.id = id;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code invite_code} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> inviteCode() {
            return Optional.ofNullable(inviteCode);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_query_by_id");
            if (root == null) {
                return Optional.empty();
            }

            var inviteCode = root.getString("invite_code");
            var id = root.getString("id");

            return Optional.of(new Response(inviteCode, id));
        }
    }
}
