package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Updates a single property on a group (membership approval, member add
 * mode, announcement-only flag, etc.) by issuing the corresponding MEX
 * mutation.
 *
 * <p>The mutation takes the group id together with a serialised update
 * payload that encodes the property being changed and its new value. The
 * response echoes the affected group id and its resulting state so that the
 * caller can compare against the local cache.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: the compiled
 * GraphQL mutation is dispatched through {@code WAWebMexClient.fetchQuery}
 * and returns the updated {@code xwa2_group_update_*} payload.
 */
public final class UpdateGroupPropertyMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexUpdateGroupPropertyJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: corresponds
     * to the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "9418211574894172";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexUpdateGroupProperty
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexUpdateGroupProperty"}.
     */
    public static final String OPERATION_NAME = "mexUpdateGroupProperty";
    /**
     * The target group id bound to the {@code group_id} GraphQL variable.
     */
    private final String groupId;

    /**
     * The serialised property update payload bound to the {@code update}
     * GraphQL variable.
     */
    private final String update;

    /**
     * Constructs a new request carrying the {@code group_id} and
     * {@code update} GraphQL variables for the mutation.
     *
     * @param groupId the target group id
     * @param update  the serialised JSON payload describing the property
     *                change
     */
    public UpdateGroupPropertyMexRequest(String groupId, String update) {
        this.groupId = groupId;
        this.update = update;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: mirrors
     * the compiled mutation's {@code argumentDefinitions} (named
     * {@code group_id} and {@code update}) which are bound to the
     * {@code xwa2_group_update_property} selection at dispatch time.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql", exports = "argumentDefinitions",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            if (groupId != null) {
                writer.writeName("group_id");
                writer.writeColon();
                writer.writeString(groupId);
            }
            if (update != null) {
                writer.writeName("update");
                writer.writeColon();
                writer.writeString(update);
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
