package com.github.auties00.cobalt.node.mex.json.group;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Updates a single property on a group (membership approval, member add
 * mode, announcement-only flag, etc.) by issuing the corresponding MEX
 * mutation.
 *
 * <p>The mutation takes the group id together with a serialised update
 * payload that encodes the property being changed and its new value. The
 * response echoes the affected group id and its resulting state so that the
 * caller can compare against the local cache.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: the compiled
 * GraphQL mutation is dispatched through {@code WAWebMexClient.fetchQuery}
 * and returns the updated {@code xwa2_group_update_*} payload.
 */
@WhatsAppWebModule(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql")
public sealed interface UpdateGroupPropertyMex extends MexJsonOperation permits UpdateGroupPropertyMex.Request, UpdateGroupPropertyMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexUpdateGroupPropertyJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: corresponds
     * to the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9418211574894172";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements UpdateGroupPropertyMex {
        private final String groupId;
        private final String update;

        public Request(String groupId, String update) {
            this.groupId = groupId;
            this.update = update;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: the two
         * variables are the target {@code group_id} and the serialised
         * {@code update} payload describing the property change.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (groupId != null) {
                    writer.writeName("group_id");
                    writer.writeColon();
                    writer.writeString(groupId);
                }
                if (update != null) {
                    writer.writeName("update");
                    writer.writeColon();
                    writer.writeString(update);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements UpdateGroupPropertyMex {
        private final String id;
        private final String state;

        private Response(String id, String state) {
            this.id = id;
            this.state = state;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexUpdateGroupPropertyJobMutation.graphql: reads
         * the group {@code id} and resulting {@code state} from the mutation
         * payload.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexUpdateGroupPropertyJobMutation.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        /**
         * Returns the {@code state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> state() {
            return Optional.ofNullable(state);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_group_update_property");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");
            var state = root.getString("state");

            return Optional.of(new Response(id, state));
        }
    }
}
