package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX mutation operation for the {@code DemoteNewsletterAdmin} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface DemoteNewsletterAdminMex extends MexJsonOperation permits DemoteNewsletterAdminMex.Request, DemoteNewsletterAdminMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9880997548630971";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements DemoteNewsletterAdminMex {
        private final String newsletterId;
        private final String userId;

        public Request(String newsletterId, String userId) {
            this.newsletterId = newsletterId;
            this.userId = userId;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (newsletterId != null) {
                    writer.writeName("newsletter_id");
                    writer.writeColon();
                    writer.writeString(newsletterId);
                }
                if (userId != null) {
                    writer.writeName("user_id");
                    writer.writeColon();
                    writer.writeString(userId);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements DemoteNewsletterAdminMex {
        private final String id;

        private Response(String id) {
            this.id = id;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> id() {
            return Optional.ofNullable(id);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_admin_demote");
            if (root == null) {
                return Optional.empty();
            }

            var id = root.getString("id");

            return Optional.of(new Response(id));
        }
    }
}
