package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterPollVoters} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterPollVotersMex extends MexJsonOperation permits FetchNewsletterPollVotersMex.Request, FetchNewsletterPollVotersMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9407762219322536";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterPollVotersMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterPollVotersMex {
        private final List<Votes> votes;

        private Response(List<Votes> votes) {
            this.votes = votes;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code votes} field.
         *
         * @return the list of values, empty if absent
         */
        public List<Votes> votes() {
            return votes;
        }

        /**
         * A parsed {@code Votes} object.
         */
        public static final class Votes {
            private final String voteHash;
            private final VoterList voterList;

            private Votes(String voteHash, VoterList voterList) {
                this.voteHash = voteHash;
                this.voterList = voterList;
            }

            /**
             * Returns the {@code vote_hash} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> voteHash() {
                return Optional.ofNullable(voteHash);
            }

            /**
             * Returns the {@code voter_list} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<VoterList> voterList() {
                return Optional.ofNullable(voterList);
            }

            /**
             * A parsed {@code VoterList} object.
             */
            public static final class VoterList {
                private final List<Edges> edges;

                private VoterList(List<Edges> edges) {
                    this.edges = edges;
                }

                /**
                 * Returns the {@code edges} field.
                 *
                 * @return the list of values, empty if absent
                 */
                public List<Edges> edges() {
                    return edges;
                }

                /**
                 * A parsed {@code Edges} object.
                 */
                public static final class Edges {
                    private final Long actionTime;
                    private final Node node;

                    private Edges(Long actionTime, Node node) {
                        this.actionTime = actionTime;
                        this.node = node;
                    }

                    /**
                     * Returns the {@code action_time} field.
                     *
                     * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
                     */
                    public Optional<Instant> actionTime() {
                        return Optional.ofNullable(actionTime).map(Instant::ofEpochSecond);
                    }

                    /**
                     * Returns the {@code node} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<Node> node() {
                        return Optional.ofNullable(node);
                    }

                    /**
                     * A parsed {@code Node} object.
                     */
                    public static final class Node {
                        private final String id;

                        private Node(String id) {
                            this.id = id;
                        }

                        /**
                         * Returns the {@code id} field.
                         *
                         * @return an {@link Optional} containing the value, or empty if absent
                         */
                        public Optional<String> id() {
                            return Optional.ofNullable(id);
                        }

                        /**
                         * Parses a {@code Node} from the given JSON object.
                         *
                         * @param obj the JSON object to parse
                         * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                         */
                        static Optional<Node> of(JSONObject obj) {
                            if (obj == null) {
                                return Optional.empty();
                            }

                            var id = obj.getString("id");
                            return Optional.of(new Node(id));
                        }

                        /**
                         * Parses a list of {@code Node} from the given JSON array.
                         *
                         * @param arr the JSON array to parse
                         * @return the list of parsed results, empty if {@code arr} is {@code null}
                         */
                        static List<Node> ofArray(JSONArray arr) {
                            if (arr == null) {
                                return List.of();
                            }

                            var result = new ArrayList<Node>(arr.size());
                            for (int i = 0; i < arr.size(); i++) {
                                of(arr.getJSONObject(i)).ifPresent(result::add);
                            }
                            return result;
                        }
                    }

                    /**
                     * Parses a {@code Edges} from the given JSON object.
                     *
                     * @param obj the JSON object to parse
                     * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                     */
                    static Optional<Edges> of(JSONObject obj) {
                        if (obj == null) {
                            return Optional.empty();
                        }

                        var actionTime = obj.getLong("action_time");
                        var node = Node.of(obj.getJSONObject("node")).orElse(null);
                        return Optional.of(new Edges(actionTime, node));
                    }

                    /**
                     * Parses a list of {@code Edges} from the given JSON array.
                     *
                     * @param arr the JSON array to parse
                     * @return the list of parsed results, empty if {@code arr} is {@code null}
                     */
                    static List<Edges> ofArray(JSONArray arr) {
                        if (arr == null) {
                            return List.of();
                        }

                        var result = new ArrayList<Edges>(arr.size());
                        for (int i = 0; i < arr.size(); i++) {
                            of(arr.getJSONObject(i)).ifPresent(result::add);
                        }
                        return result;
                    }
                }

                /**
                 * Parses a {@code VoterList} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<VoterList> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var edges = Edges.ofArray(obj.getJSONArray("edges"));
                    return Optional.of(new VoterList(edges));
                }

                /**
                 * Parses a list of {@code VoterList} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<VoterList> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<VoterList>(arr.size());
                    for (int i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Votes} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Votes> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var voteHash = obj.getString("vote_hash");
                var voterList = VoterList.of(obj.getJSONObject("voter_list")).orElse(null);
                return Optional.of(new Votes(voteHash, voterList));
            }

            /**
             * Parses a list of {@code Votes} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Votes> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Votes>(arr.size());
                for (int i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("voter_list");
            if (root == null) {
                return Optional.empty();
            }

            var votes = Votes.ofArray(root.getJSONArray("votes"));

            return Optional.of(new Response(votes));
        }
    }
}
