package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterReports} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterReportsMex extends MexJsonOperation permits FetchNewsletterReportsMex.Request, FetchNewsletterReportsMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "25246702401624388";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterReportsMex {

        public Request() {
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterReportsMex {
        private final List<ChannelsReports> channelsReports;

        private Response(List<ChannelsReports> channelsReports) {
            this.channelsReports = channelsReports;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code channels_reports} field.
         *
         * @return the list of values, empty if absent
         */
        public List<ChannelsReports> channelsReports() {
            return channelsReports;
        }

        /**
         * A parsed {@code ChannelsReports} object.
         */
        public static final class ChannelsReports {
            private final String reportId;
            private final String status;
            private final Long creationTime;
            private final Long lastUpdateTime;
            private final String channelName;
            private final String channelJid;
            private final String serverMsgId;
            private final String responseServerMsgId;
            private final String notifyName;
            private final Appeal appeal;

            private ChannelsReports(String reportId, String status, Long creationTime, Long lastUpdateTime, String channelName, String channelJid, String serverMsgId, String responseServerMsgId, String notifyName, Appeal appeal) {
                this.reportId = reportId;
                this.status = status;
                this.creationTime = creationTime;
                this.lastUpdateTime = lastUpdateTime;
                this.channelName = channelName;
                this.channelJid = channelJid;
                this.serverMsgId = serverMsgId;
                this.responseServerMsgId = responseServerMsgId;
                this.notifyName = notifyName;
                this.appeal = appeal;
            }

            /**
             * Returns the {@code report_id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> reportId() {
                return Optional.ofNullable(reportId);
            }

            /**
             * Returns the {@code status} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> status() {
                return Optional.ofNullable(status);
            }

            /**
             * Returns the {@code creation_time} field.
             *
             * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
             */
            public Optional<Instant> creationTime() {
                return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
            }

            /**
             * Returns the {@code last_update_time} field.
             *
             * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
             */
            public Optional<Instant> lastUpdateTime() {
                return Optional.ofNullable(lastUpdateTime).map(Instant::ofEpochSecond);
            }

            /**
             * Returns the {@code channel_name} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> channelName() {
                return Optional.ofNullable(channelName);
            }

            /**
             * Returns the {@code channel_jid} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> channelJid() {
                return Optional.ofNullable(channelJid);
            }

            /**
             * Returns the {@code server_msg_id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> serverMsgId() {
                return Optional.ofNullable(serverMsgId);
            }

            /**
             * Returns the {@code response_server_msg_id} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> responseServerMsgId() {
                return Optional.ofNullable(responseServerMsgId);
            }

            /**
             * Returns the {@code notify_name} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> notifyName() {
                return Optional.ofNullable(notifyName);
            }

            /**
             * Returns the {@code appeal} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<Appeal> appeal() {
                return Optional.ofNullable(appeal);
            }

            /**
             * A parsed {@code Appeal} object.
             */
            public static final class Appeal {
                private final String state;
                private final String appealReason;
                private final Long creationTime;
                private final String reportId;
                private final String appealId;

                private Appeal(String state, String appealReason, Long creationTime, String reportId, String appealId) {
                    this.state = state;
                    this.appealReason = appealReason;
                    this.creationTime = creationTime;
                    this.reportId = reportId;
                    this.appealId = appealId;
                }

                /**
                 * Returns the {@code state} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> state() {
                    return Optional.ofNullable(state);
                }

                /**
                 * Returns the {@code appeal_reason} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> appealReason() {
                    return Optional.ofNullable(appealReason);
                }

                /**
                 * Returns the {@code creation_time} field.
                 *
                 * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
                 */
                public Optional<Instant> creationTime() {
                    return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
                }

                /**
                 * Returns the {@code report_id} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> reportId() {
                    return Optional.ofNullable(reportId);
                }

                /**
                 * Returns the {@code appeal_id} field.
                 *
                 * @return an {@link Optional} containing the value, or empty if absent
                 */
                public Optional<String> appealId() {
                    return Optional.ofNullable(appealId);
                }

                /**
                 * Parses a {@code Appeal} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<Appeal> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var state = obj.getString("state");
                    var appealReason = obj.getString("appeal_reason");
                    var creationTime = obj.getLong("creation_time");
                    var reportId = obj.getString("report_id");
                    var appealId = obj.getString("appeal_id");
                    return Optional.of(new Appeal(state, appealReason, creationTime, reportId, appealId));
                }

                /**
                 * Parses a list of {@code Appeal} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<Appeal> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<Appeal>(arr.size());
                    for (var i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code ChannelsReports} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<ChannelsReports> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var reportId = obj.getString("report_id");
                var status = obj.getString("status");
                var creationTime = obj.getLong("creation_time");
                var lastUpdateTime = obj.getLong("last_update_time");
                var channelName = obj.getString("channel_name");
                var channelJid = obj.getString("channel_jid");
                var serverMsgId = obj.getString("server_msg_id");
                var responseServerMsgId = obj.getString("response_server_msg_id");
                var notifyName = obj.getString("notify_name");
                var appeal = Appeal.of(obj.getJSONObject("appeal")).orElse(null);
                return Optional.of(new ChannelsReports(reportId, status, creationTime, lastUpdateTime, channelName, channelJid, serverMsgId, responseServerMsgId, notifyName, appeal));
            }

            /**
             * Parses a list of {@code ChannelsReports} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<ChannelsReports> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<ChannelsReports>(arr.size());
                for (var i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_channels_reports");
            if (root == null) {
                return Optional.empty();
            }

            var channelsReports = ChannelsReports.ofArray(root.getJSONArray("channels_reports"));

            return Optional.of(new Response(channelsReports));
        }
    }
}
