package com.github.auties00.cobalt.node.mex.json.community;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Transfers ownership of a community from the current owner to another
 * admin, updating the server-side role mapping for the group.
 *
 * <p>This mutation is issued from the "transfer ownership" action in the
 * community settings. The response echoes the affected group id and the
 * resulting LID migration state (addressing mode) so that the client can
 * update its local view of the community before replaying cached actions.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexTransferCommunityOwnershipJob.mexTransferCommunityOwnershipJob:
 * sends {@code WAWebMexTransferCommunityOwnershipJobMutation} through
 * {@code WAWebMexClient.fetchQuery} and reads
 * {@code xwa2_group_update_users_role}.
 */
public final class TransferCommunityOwnershipMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexTransferCommunityOwnershipJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexTransferCommunityOwnershipJobMutation.graphql:
     * corresponds to the {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexTransferCommunityOwnershipJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "29643783178598899";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexTransferCommunityOwnershipJob
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexTransferCommunityOwnershipJobMutation.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexTransferCommunityOwnershipJob"}.
     */
    public static final String OPERATION_NAME = "mexTransferCommunityOwnershipJob";
    private final String input;

    public TransferCommunityOwnershipMexRequest(String input) {
        this.input = input;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexTransferCommunityOwnershipJobMutation.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexTransferCommunityOwnershipJobMutation.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @implNote WAWebMexTransferCommunityOwnershipJob.mexTransferCommunityOwnershipJob:
     * the {@code input} variable is a serialised object containing the
     * community id and the new owner's id.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexTransferCommunityOwnershipJob", exports = "mexTransferCommunityOwnershipJob",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            if (input != null) {
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
