package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterIsDomainPreviewable} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterIsDomainPreviewableMex extends MexJsonOperation permits FetchNewsletterIsDomainPreviewableMex.Request, FetchNewsletterIsDomainPreviewableMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "9849510985088294";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterIsDomainPreviewableMex {
        private final String urlDomains;

        public Request(String urlDomains) {
            this.urlDomains = urlDomains;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (urlDomains != null) {
                    writer.writeName("url_domains");
                    writer.writeColon();
                    writer.writeString(urlDomains);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterIsDomainPreviewableMex {
        private final List<UrlPreviews> urlPreviews;

        private Response(List<UrlPreviews> urlPreviews) {
            this.urlPreviews = urlPreviews;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code url_previews} field.
         *
         * @return the list of values, empty if absent
         */
        public List<UrlPreviews> urlPreviews() {
            return urlPreviews;
        }

        /**
         * A parsed {@code UrlPreviews} object.
         */
        public static final class UrlPreviews {
            private final String urlDomain;
            private final Boolean isPreviewable;

            private UrlPreviews(String urlDomain, Boolean isPreviewable) {
                this.urlDomain = urlDomain;
                this.isPreviewable = isPreviewable;
            }

            /**
             * Returns the {@code url_domain} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> urlDomain() {
                return Optional.ofNullable(urlDomain);
            }

            /**
             * Returns the {@code is_previewable} field.
             *
             * @return {@code true} if the value is present and true, {@code false} otherwise
             */
            public boolean isPreviewable() {
                return isPreviewable != null && isPreviewable;
            }

            /**
             * Parses a {@code UrlPreviews} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<UrlPreviews> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var urlDomain = obj.getString("url_domain");
                var isPreviewable = obj.getBoolean("is_previewable");
                return Optional.of(new UrlPreviews(urlDomain, isPreviewable));
            }

            /**
             * Parses a list of {@code UrlPreviews} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<UrlPreviews> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<UrlPreviews>(arr.size());
                for (int i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_message_integrity");
            if (root == null) {
                return Optional.empty();
            }

            var urlPreviews = UrlPreviews.ofArray(root.getJSONArray("url_previews"));

            return Optional.of(new Response(urlPreviews));
        }
    }
}
