package com.github.auties00.cobalt.node.mex.json.newsletter;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * A MEX query operation for the {@code FetchNewsletterMessageReactionSenderList} endpoint.
 *
 * <p>This is a sealed interface generated by the mex-codegen tool.
 * Manual edits will be overwritten on the next generation run.
 */
public sealed interface FetchNewsletterMessageReactionSenderListMex extends MexJsonOperation permits FetchNewsletterMessageReactionSenderListMex.Request, FetchNewsletterMessageReactionSenderListMex.Response {
    /**
     * The numeric query identifier for this MEX operation.
     */
    String QUERY_ID = "29575462448733991";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchNewsletterMessageReactionSenderListMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Builds the MEX IQ stanza for this request.
         *
         * @return the IQ {@link NodeBuilder} ready to be sent
         */
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchNewsletterMessageReactionSenderListMex {
        private final List<Reactions> reactions;

        private Response(List<Reactions> reactions) {
            this.reactions = reactions;
        }

        /**
         * Parses a MEX response from the given IQ response node.
         *
         * @param node the IQ response node
         * @return an {@link Optional} containing the parsed response, or empty if parsing fails
         */
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code reactions} field.
         *
         * @return the list of values, empty if absent
         */
        public List<Reactions> reactions() {
            return reactions;
        }

        /**
         * A parsed {@code Reactions} object.
         */
        public static final class Reactions {
            private final String reactionCode;
            private final SenderList senderList;

            private Reactions(String reactionCode, SenderList senderList) {
                this.reactionCode = reactionCode;
                this.senderList = senderList;
            }

            /**
             * Returns the {@code reaction_code} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<String> reactionCode() {
                return Optional.ofNullable(reactionCode);
            }

            /**
             * Returns the {@code sender_list} field.
             *
             * @return an {@link Optional} containing the value, or empty if absent
             */
            public Optional<SenderList> senderList() {
                return Optional.ofNullable(senderList);
            }

            /**
             * A parsed {@code SenderList} object.
             */
            public static final class SenderList {
                private final List<Edges> edges;

                private SenderList(List<Edges> edges) {
                    this.edges = edges;
                }

                /**
                 * Returns the {@code edges} field.
                 *
                 * @return the list of values, empty if absent
                 */
                public List<Edges> edges() {
                    return edges;
                }

                /**
                 * A parsed {@code Edges} object.
                 */
                public static final class Edges {
                    private final Node node;

                    private Edges(Node node) {
                        this.node = node;
                    }

                    /**
                     * Returns the {@code node} field.
                     *
                     * @return an {@link Optional} containing the value, or empty if absent
                     */
                    public Optional<Node> node() {
                        return Optional.ofNullable(node);
                    }

                    /**
                     * A parsed {@code Node} object.
                     */
                    public static final class Node {
                        private final String id;
                        private final String profilePicDirectPath;

                        private Node(String id, String profilePicDirectPath) {
                            this.id = id;
                            this.profilePicDirectPath = profilePicDirectPath;
                        }

                        /**
                         * Returns the {@code id} field.
                         *
                         * @return an {@link Optional} containing the value, or empty if absent
                         */
                        public Optional<String> id() {
                            return Optional.ofNullable(id);
                        }

                        /**
                         * Returns the {@code profile_pic_direct_path} field.
                         *
                         * @return an {@link Optional} containing the value, or empty if absent
                         */
                        public Optional<String> profilePicDirectPath() {
                            return Optional.ofNullable(profilePicDirectPath);
                        }

                        /**
                         * Parses a {@code Node} from the given JSON object.
                         *
                         * @param obj the JSON object to parse
                         * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                         */
                        static Optional<Node> of(JSONObject obj) {
                            if (obj == null) {
                                return Optional.empty();
                            }

                            var id = obj.getString("id");
                            var profilePicDirectPath = obj.getString("profile_pic_direct_path");
                            return Optional.of(new Node(id, profilePicDirectPath));
                        }

                        /**
                         * Parses a list of {@code Node} from the given JSON array.
                         *
                         * @param arr the JSON array to parse
                         * @return the list of parsed results, empty if {@code arr} is {@code null}
                         */
                        static List<Node> ofArray(JSONArray arr) {
                            if (arr == null) {
                                return List.of();
                            }

                            var result = new ArrayList<Node>(arr.size());
                            for (int i = 0; i < arr.size(); i++) {
                                of(arr.getJSONObject(i)).ifPresent(result::add);
                            }
                            return result;
                        }
                    }

                    /**
                     * Parses a {@code Edges} from the given JSON object.
                     *
                     * @param obj the JSON object to parse
                     * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                     */
                    static Optional<Edges> of(JSONObject obj) {
                        if (obj == null) {
                            return Optional.empty();
                        }

                        var node = Node.of(obj.getJSONObject("node")).orElse(null);
                        return Optional.of(new Edges(node));
                    }

                    /**
                     * Parses a list of {@code Edges} from the given JSON array.
                     *
                     * @param arr the JSON array to parse
                     * @return the list of parsed results, empty if {@code arr} is {@code null}
                     */
                    static List<Edges> ofArray(JSONArray arr) {
                        if (arr == null) {
                            return List.of();
                        }

                        var result = new ArrayList<Edges>(arr.size());
                        for (int i = 0; i < arr.size(); i++) {
                            of(arr.getJSONObject(i)).ifPresent(result::add);
                        }
                        return result;
                    }
                }

                /**
                 * Parses a {@code SenderList} from the given JSON object.
                 *
                 * @param obj the JSON object to parse
                 * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
                 */
                static Optional<SenderList> of(JSONObject obj) {
                    if (obj == null) {
                        return Optional.empty();
                    }

                    var edges = Edges.ofArray(obj.getJSONArray("edges"));
                    return Optional.of(new SenderList(edges));
                }

                /**
                 * Parses a list of {@code SenderList} from the given JSON array.
                 *
                 * @param arr the JSON array to parse
                 * @return the list of parsed results, empty if {@code arr} is {@code null}
                 */
                static List<SenderList> ofArray(JSONArray arr) {
                    if (arr == null) {
                        return List.of();
                    }

                    var result = new ArrayList<SenderList>(arr.size());
                    for (int i = 0; i < arr.size(); i++) {
                        of(arr.getJSONObject(i)).ifPresent(result::add);
                    }
                    return result;
                }
            }

            /**
             * Parses a {@code Reactions} from the given JSON object.
             *
             * @param obj the JSON object to parse
             * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
             */
            static Optional<Reactions> of(JSONObject obj) {
                if (obj == null) {
                    return Optional.empty();
                }

                var reactionCode = obj.getString("reaction_code");
                var senderList = SenderList.of(obj.getJSONObject("sender_list")).orElse(null);
                return Optional.of(new Reactions(reactionCode, senderList));
            }

            /**
             * Parses a list of {@code Reactions} from the given JSON array.
             *
             * @param arr the JSON array to parse
             * @return the list of parsed results, empty if {@code arr} is {@code null}
             */
            static List<Reactions> ofArray(JSONArray arr) {
                if (arr == null) {
                    return List.of();
                }

                var result = new ArrayList<Reactions>(arr.size());
                for (int i = 0; i < arr.size(); i++) {
                    of(arr.getJSONObject(i)).ifPresent(result::add);
                }
                return result;
            }
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletters_reaction_sender_list");
            if (root == null) {
                return Optional.empty();
            }

            var reactions = Reactions.ofArray(root.getJSONArray("reactions"));

            return Optional.of(new Response(reactions));
        }
    }
}
