// Generated by jextract

package com.github.auties00.cobalt.calls2.media.video.vpx.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class CobaltVpx extends CobaltVpx$shared {

    CobaltVpx() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int COBALT_VPX_CODEC_VP8 = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_CODEC_VP8 0
     * }
     */
    public static int COBALT_VPX_CODEC_VP8() {
        return COBALT_VPX_CODEC_VP8;
    }
    private static final int COBALT_VPX_CODEC_VP9 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_CODEC_VP9 1
     * }
     */
    public static int COBALT_VPX_CODEC_VP9() {
        return COBALT_VPX_CODEC_VP9;
    }
    private static final int COBALT_VPX_PLANE_Y = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_PLANE_Y 0
     * }
     */
    public static int COBALT_VPX_PLANE_Y() {
        return COBALT_VPX_PLANE_Y;
    }
    private static final int COBALT_VPX_PLANE_U = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_PLANE_U 1
     * }
     */
    public static int COBALT_VPX_PLANE_U() {
        return COBALT_VPX_PLANE_U;
    }
    private static final int COBALT_VPX_PLANE_V = (int)2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_PLANE_V 2
     * }
     */
    public static int COBALT_VPX_PLANE_V() {
        return COBALT_VPX_PLANE_V;
    }
    private static final int COBALT_VPX_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_OK 0
     * }
     */
    public static int COBALT_VPX_OK() {
        return COBALT_VPX_OK;
    }

    private static class cobalt_vpx_encoder_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_encoder_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_create(int32_t codec, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed, void **outCtx)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_encoder_create$descriptor() {
        return cobalt_vpx_encoder_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_create(int32_t codec, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed, void **outCtx)
     * }
     */
    public static MethodHandle cobalt_vpx_encoder_create$handle() {
        return cobalt_vpx_encoder_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_create(int32_t codec, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed, void **outCtx)
     * }
     */
    public static MemorySegment cobalt_vpx_encoder_create$address() {
        return cobalt_vpx_encoder_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_create(int32_t codec, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed, void **outCtx)
     * }
     */
    public static int cobalt_vpx_encoder_create(int codec, int width, int height, int targetBitrateBps, int frameRate, int minQuantizer, int maxQuantizer, int dropframeThresh, int kfMaxDist, int cpuUsed, MemorySegment outCtx) {
        var mh$ = cobalt_vpx_encoder_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_encoder_create", codec, width, height, targetBitrateBps, frameRate, minQuantizer, maxQuantizer, dropframeThresh, kfMaxDist, cpuUsed, outCtx);
            }
            return (int)mh$.invokeExact(codec, width, height, targetBitrateBps, frameRate, minQuantizer, maxQuantizer, dropframeThresh, kfMaxDist, cpuUsed, outCtx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_encoder_reconfigure {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_encoder_reconfigure");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_reconfigure(void *ctx, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_encoder_reconfigure$descriptor() {
        return cobalt_vpx_encoder_reconfigure.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_reconfigure(void *ctx, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed)
     * }
     */
    public static MethodHandle cobalt_vpx_encoder_reconfigure$handle() {
        return cobalt_vpx_encoder_reconfigure.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_reconfigure(void *ctx, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed)
     * }
     */
    public static MemorySegment cobalt_vpx_encoder_reconfigure$address() {
        return cobalt_vpx_encoder_reconfigure.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_reconfigure(void *ctx, int32_t width, int32_t height, int32_t targetBitrateBps, int32_t frameRate, int32_t minQuantizer, int32_t maxQuantizer, int32_t dropframeThresh, int32_t kfMaxDist, int32_t cpuUsed)
     * }
     */
    public static int cobalt_vpx_encoder_reconfigure(MemorySegment ctx, int width, int height, int targetBitrateBps, int frameRate, int minQuantizer, int maxQuantizer, int dropframeThresh, int kfMaxDist, int cpuUsed) {
        var mh$ = cobalt_vpx_encoder_reconfigure.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_encoder_reconfigure", ctx, width, height, targetBitrateBps, frameRate, minQuantizer, maxQuantizer, dropframeThresh, kfMaxDist, cpuUsed);
            }
            return (int)mh$.invokeExact(ctx, width, height, targetBitrateBps, frameRate, minQuantizer, maxQuantizer, dropframeThresh, kfMaxDist, cpuUsed);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_encoder_encode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_LONG_LONG,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_LONG_LONG,
            CobaltVpx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_encoder_encode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t pts, int32_t forceKeyframe)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_encoder_encode$descriptor() {
        return cobalt_vpx_encoder_encode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t pts, int32_t forceKeyframe)
     * }
     */
    public static MethodHandle cobalt_vpx_encoder_encode$handle() {
        return cobalt_vpx_encoder_encode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t pts, int32_t forceKeyframe)
     * }
     */
    public static MemorySegment cobalt_vpx_encoder_encode$address() {
        return cobalt_vpx_encoder_encode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t pts, int32_t forceKeyframe)
     * }
     */
    public static int cobalt_vpx_encoder_encode(MemorySegment ctx, MemorySegment i420, long len, int width, int height, long pts, int forceKeyframe) {
        var mh$ = cobalt_vpx_encoder_encode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_encoder_encode", ctx, i420, len, width, height, pts, forceKeyframe);
            }
            return (int)mh$.invokeExact(ctx, i420, len, width, height, pts, forceKeyframe);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_encoder_get_packet {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_encoder_get_packet");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKey)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_encoder_get_packet$descriptor() {
        return cobalt_vpx_encoder_get_packet.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKey)
     * }
     */
    public static MethodHandle cobalt_vpx_encoder_get_packet$handle() {
        return cobalt_vpx_encoder_get_packet.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKey)
     * }
     */
    public static MemorySegment cobalt_vpx_encoder_get_packet$address() {
        return cobalt_vpx_encoder_get_packet.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKey)
     * }
     */
    public static int cobalt_vpx_encoder_get_packet(MemorySegment ctx, MemorySegment outBuf, MemorySegment outLen, MemorySegment outIsKey) {
        var mh$ = cobalt_vpx_encoder_get_packet.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_encoder_get_packet", ctx, outBuf, outLen, outIsKey);
            }
            return (int)mh$.invokeExact(ctx, outBuf, outLen, outIsKey);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_encoder_destroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_encoder_destroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_destroy(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_encoder_destroy$descriptor() {
        return cobalt_vpx_encoder_destroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_destroy(void *ctx)
     * }
     */
    public static MethodHandle cobalt_vpx_encoder_destroy$handle() {
        return cobalt_vpx_encoder_destroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_destroy(void *ctx)
     * }
     */
    public static MemorySegment cobalt_vpx_encoder_destroy$address() {
        return cobalt_vpx_encoder_destroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_encoder_destroy(void *ctx)
     * }
     */
    public static int cobalt_vpx_encoder_destroy(MemorySegment ctx) {
        var mh$ = cobalt_vpx_encoder_destroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_encoder_destroy", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_decoder_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_decoder_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_create(int32_t codec, int32_t width, int32_t height, void **outCtx)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_decoder_create$descriptor() {
        return cobalt_vpx_decoder_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_create(int32_t codec, int32_t width, int32_t height, void **outCtx)
     * }
     */
    public static MethodHandle cobalt_vpx_decoder_create$handle() {
        return cobalt_vpx_decoder_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_create(int32_t codec, int32_t width, int32_t height, void **outCtx)
     * }
     */
    public static MemorySegment cobalt_vpx_decoder_create$address() {
        return cobalt_vpx_decoder_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_create(int32_t codec, int32_t width, int32_t height, void **outCtx)
     * }
     */
    public static int cobalt_vpx_decoder_create(int codec, int width, int height, MemorySegment outCtx) {
        var mh$ = cobalt_vpx_decoder_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_decoder_create", codec, width, height, outCtx);
            }
            return (int)mh$.invokeExact(codec, width, height, outCtx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_decoder_decode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_decoder_decode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_decoder_decode$descriptor() {
        return cobalt_vpx_decoder_decode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static MethodHandle cobalt_vpx_decoder_decode$handle() {
        return cobalt_vpx_decoder_decode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static MemorySegment cobalt_vpx_decoder_decode$address() {
        return cobalt_vpx_decoder_decode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static int cobalt_vpx_decoder_decode(MemorySegment ctx, MemorySegment data, long len) {
        var mh$ = cobalt_vpx_decoder_decode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_decoder_decode", ctx, data, len);
            }
            return (int)mh$.invokeExact(ctx, data, len);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_decoder_get_frame {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_decoder_get_frame");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_decoder_get_frame$descriptor() {
        return cobalt_vpx_decoder_get_frame.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static MethodHandle cobalt_vpx_decoder_get_frame$handle() {
        return cobalt_vpx_decoder_get_frame.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static MemorySegment cobalt_vpx_decoder_get_frame$address() {
        return cobalt_vpx_decoder_get_frame.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static int cobalt_vpx_decoder_get_frame(MemorySegment ctx, MemorySegment outImg) {
        var mh$ = cobalt_vpx_decoder_get_frame.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_decoder_get_frame", ctx, outImg);
            }
            return (int)mh$.invokeExact(ctx, outImg);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_img_plane {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_POINTER,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_img_plane");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_vpx_img_plane(void *img, int32_t plane)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_img_plane$descriptor() {
        return cobalt_vpx_img_plane.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_vpx_img_plane(void *img, int32_t plane)
     * }
     */
    public static MethodHandle cobalt_vpx_img_plane$handle() {
        return cobalt_vpx_img_plane.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_vpx_img_plane(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_vpx_img_plane$address() {
        return cobalt_vpx_img_plane.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const uint8_t *cobalt_vpx_img_plane(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_vpx_img_plane(MemorySegment img, int plane) {
        var mh$ = cobalt_vpx_img_plane.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_img_plane", img, plane);
            }
            return (MemorySegment)mh$.invokeExact(img, plane);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_img_stride {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER,
            CobaltVpx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_img_stride");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_stride(void *img, int32_t plane)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_img_stride$descriptor() {
        return cobalt_vpx_img_stride.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_stride(void *img, int32_t plane)
     * }
     */
    public static MethodHandle cobalt_vpx_img_stride$handle() {
        return cobalt_vpx_img_stride.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_stride(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_vpx_img_stride$address() {
        return cobalt_vpx_img_stride.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_stride(void *img, int32_t plane)
     * }
     */
    public static int cobalt_vpx_img_stride(MemorySegment img, int plane) {
        var mh$ = cobalt_vpx_img_stride.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_img_stride", img, plane);
            }
            return (int)mh$.invokeExact(img, plane);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_img_width {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_img_width");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_width(void *img)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_img_width$descriptor() {
        return cobalt_vpx_img_width.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_width(void *img)
     * }
     */
    public static MethodHandle cobalt_vpx_img_width$handle() {
        return cobalt_vpx_img_width.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_width(void *img)
     * }
     */
    public static MemorySegment cobalt_vpx_img_width$address() {
        return cobalt_vpx_img_width.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_width(void *img)
     * }
     */
    public static int cobalt_vpx_img_width(MemorySegment img) {
        var mh$ = cobalt_vpx_img_width.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_img_width", img);
            }
            return (int)mh$.invokeExact(img);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_img_height {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_img_height");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_height(void *img)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_img_height$descriptor() {
        return cobalt_vpx_img_height.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_height(void *img)
     * }
     */
    public static MethodHandle cobalt_vpx_img_height$handle() {
        return cobalt_vpx_img_height.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_height(void *img)
     * }
     */
    public static MemorySegment cobalt_vpx_img_height$address() {
        return cobalt_vpx_img_height.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_img_height(void *img)
     * }
     */
    public static int cobalt_vpx_img_height(MemorySegment img) {
        var mh$ = cobalt_vpx_img_height.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_img_height", img);
            }
            return (int)mh$.invokeExact(img);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_decoder_destroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_INT,
            CobaltVpx.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_decoder_destroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_destroy(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_decoder_destroy$descriptor() {
        return cobalt_vpx_decoder_destroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_destroy(void *ctx)
     * }
     */
    public static MethodHandle cobalt_vpx_decoder_destroy$handle() {
        return cobalt_vpx_decoder_destroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_destroy(void *ctx)
     * }
     */
    public static MemorySegment cobalt_vpx_decoder_destroy$address() {
        return cobalt_vpx_decoder_destroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_vpx_decoder_destroy(void *ctx)
     * }
     */
    public static int cobalt_vpx_decoder_destroy(MemorySegment ctx) {
        var mh$ = cobalt_vpx_decoder_destroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_decoder_destroy", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_vpx_strerror {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltVpx.C_POINTER,
            CobaltVpx.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_vpx_strerror");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *cobalt_vpx_strerror(int32_t err)
     * }
     */
    public static FunctionDescriptor cobalt_vpx_strerror$descriptor() {
        return cobalt_vpx_strerror.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *cobalt_vpx_strerror(int32_t err)
     * }
     */
    public static MethodHandle cobalt_vpx_strerror$handle() {
        return cobalt_vpx_strerror.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *cobalt_vpx_strerror(int32_t err)
     * }
     */
    public static MemorySegment cobalt_vpx_strerror$address() {
        return cobalt_vpx_strerror.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *cobalt_vpx_strerror(int32_t err)
     * }
     */
    public static MemorySegment cobalt_vpx_strerror(int err) {
        var mh$ = cobalt_vpx_strerror.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_vpx_strerror", err);
            }
            return (MemorySegment)mh$.invokeExact(err);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int COBALT_VPX_BAD_PARAM = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_BAD_PARAM -1
     * }
     */
    public static int COBALT_VPX_BAD_PARAM() {
        return COBALT_VPX_BAD_PARAM;
    }
    private static final int COBALT_VPX_NOMEM = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_NOMEM -2
     * }
     */
    public static int COBALT_VPX_NOMEM() {
        return COBALT_VPX_NOMEM;
    }
    private static final int COBALT_VPX_IMG_WRAP_FAILED = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_VPX_IMG_WRAP_FAILED -3
     * }
     */
    public static int COBALT_VPX_IMG_WRAP_FAILED() {
        return COBALT_VPX_IMG_WRAP_FAILED;
    }
}

