// Generated by jextract

package com.github.auties00.cobalt.calls2.media.video.yuv.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class CobaltYuv extends CobaltYuv$shared {

    CobaltYuv() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int COBALT_YUV_FILTER_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FILTER_NONE 0
     * }
     */
    public static int COBALT_YUV_FILTER_NONE() {
        return COBALT_YUV_FILTER_NONE;
    }
    private static final int COBALT_YUV_FILTER_LINEAR = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FILTER_LINEAR 1
     * }
     */
    public static int COBALT_YUV_FILTER_LINEAR() {
        return COBALT_YUV_FILTER_LINEAR;
    }
    private static final int COBALT_YUV_FILTER_BILINEAR = (int)2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FILTER_BILINEAR 2
     * }
     */
    public static int COBALT_YUV_FILTER_BILINEAR() {
        return COBALT_YUV_FILTER_BILINEAR;
    }
    private static final int COBALT_YUV_FILTER_BOX = (int)3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FILTER_BOX 3
     * }
     */
    public static int COBALT_YUV_FILTER_BOX() {
        return COBALT_YUV_FILTER_BOX;
    }
    private static final int COBALT_YUV_ROTATE_0 = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_ROTATE_0 0
     * }
     */
    public static int COBALT_YUV_ROTATE_0() {
        return COBALT_YUV_ROTATE_0;
    }
    private static final int COBALT_YUV_ROTATE_90 = (int)90L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_ROTATE_90 90
     * }
     */
    public static int COBALT_YUV_ROTATE_90() {
        return COBALT_YUV_ROTATE_90;
    }
    private static final int COBALT_YUV_ROTATE_180 = (int)180L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_ROTATE_180 180
     * }
     */
    public static int COBALT_YUV_ROTATE_180() {
        return COBALT_YUV_ROTATE_180;
    }
    private static final int COBALT_YUV_ROTATE_270 = (int)270L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_ROTATE_270 270
     * }
     */
    public static int COBALT_YUV_ROTATE_270() {
        return COBALT_YUV_ROTATE_270;
    }
    private static final int COBALT_YUV_FOURCC_I420 = (int)808596553L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FOURCC_I420 808596553
     * }
     */
    public static int COBALT_YUV_FOURCC_I420() {
        return COBALT_YUV_FOURCC_I420;
    }
    private static final int COBALT_YUV_FOURCC_NV12 = (int)842094158L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FOURCC_NV12 842094158
     * }
     */
    public static int COBALT_YUV_FOURCC_NV12() {
        return COBALT_YUV_FOURCC_NV12;
    }
    private static final int COBALT_YUV_FOURCC_ARGB = (int)1111970369L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_FOURCC_ARGB 1111970369
     * }
     */
    public static int COBALT_YUV_FOURCC_ARGB() {
        return COBALT_YUV_FOURCC_ARGB;
    }
    private static final int COBALT_YUV_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_OK 0
     * }
     */
    public static int COBALT_YUV_OK() {
        return COBALT_YUV_OK;
    }

    private static class cobalt_yuv_i420_to_argb {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_i420_to_argb");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_argb(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstArgb, int32_t dstStrideArgb, int32_t width, int32_t height)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_i420_to_argb$descriptor() {
        return cobalt_yuv_i420_to_argb.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_argb(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstArgb, int32_t dstStrideArgb, int32_t width, int32_t height)
     * }
     */
    public static MethodHandle cobalt_yuv_i420_to_argb$handle() {
        return cobalt_yuv_i420_to_argb.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_argb(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstArgb, int32_t dstStrideArgb, int32_t width, int32_t height)
     * }
     */
    public static MemorySegment cobalt_yuv_i420_to_argb$address() {
        return cobalt_yuv_i420_to_argb.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_argb(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstArgb, int32_t dstStrideArgb, int32_t width, int32_t height)
     * }
     */
    public static int cobalt_yuv_i420_to_argb(MemorySegment srcY, int srcStrideY, MemorySegment srcU, int srcStrideU, MemorySegment srcV, int srcStrideV, MemorySegment dstArgb, int dstStrideArgb, int width, int height) {
        var mh$ = cobalt_yuv_i420_to_argb.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_i420_to_argb", srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstArgb, dstStrideArgb, width, height);
            }
            return (int)mh$.invokeExact(srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstArgb, dstStrideArgb, width, height);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_yuv_argb_to_i420 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_argb_to_i420");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_argb_to_i420(const uint8_t *srcArgb, int32_t srcStrideArgb, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_argb_to_i420$descriptor() {
        return cobalt_yuv_argb_to_i420.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_argb_to_i420(const uint8_t *srcArgb, int32_t srcStrideArgb, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static MethodHandle cobalt_yuv_argb_to_i420$handle() {
        return cobalt_yuv_argb_to_i420.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_argb_to_i420(const uint8_t *srcArgb, int32_t srcStrideArgb, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static MemorySegment cobalt_yuv_argb_to_i420$address() {
        return cobalt_yuv_argb_to_i420.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_argb_to_i420(const uint8_t *srcArgb, int32_t srcStrideArgb, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static int cobalt_yuv_argb_to_i420(MemorySegment srcArgb, int srcStrideArgb, MemorySegment dstY, int dstStrideY, MemorySegment dstU, int dstStrideU, MemorySegment dstV, int dstStrideV, int width, int height) {
        var mh$ = cobalt_yuv_argb_to_i420.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_argb_to_i420", srcArgb, srcStrideArgb, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height);
            }
            return (int)mh$.invokeExact(srcArgb, srcStrideArgb, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_yuv_nv12_to_i420 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_nv12_to_i420");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_nv12_to_i420(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcUv, int32_t srcStrideUv, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_nv12_to_i420$descriptor() {
        return cobalt_yuv_nv12_to_i420.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_nv12_to_i420(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcUv, int32_t srcStrideUv, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static MethodHandle cobalt_yuv_nv12_to_i420$handle() {
        return cobalt_yuv_nv12_to_i420.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_nv12_to_i420(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcUv, int32_t srcStrideUv, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static MemorySegment cobalt_yuv_nv12_to_i420$address() {
        return cobalt_yuv_nv12_to_i420.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_nv12_to_i420(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcUv, int32_t srcStrideUv, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height)
     * }
     */
    public static int cobalt_yuv_nv12_to_i420(MemorySegment srcY, int srcStrideY, MemorySegment srcUv, int srcStrideUv, MemorySegment dstY, int dstStrideY, MemorySegment dstU, int dstStrideU, MemorySegment dstV, int dstStrideV, int width, int height) {
        var mh$ = cobalt_yuv_nv12_to_i420.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_nv12_to_i420", srcY, srcStrideY, srcUv, srcStrideUv, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height);
            }
            return (int)mh$.invokeExact(srcY, srcStrideY, srcUv, srcStrideUv, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_yuv_i420_to_nv12 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_i420_to_nv12");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_nv12(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstUv, int32_t dstStrideUv, int32_t width, int32_t height)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_i420_to_nv12$descriptor() {
        return cobalt_yuv_i420_to_nv12.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_nv12(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstUv, int32_t dstStrideUv, int32_t width, int32_t height)
     * }
     */
    public static MethodHandle cobalt_yuv_i420_to_nv12$handle() {
        return cobalt_yuv_i420_to_nv12.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_nv12(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstUv, int32_t dstStrideUv, int32_t width, int32_t height)
     * }
     */
    public static MemorySegment cobalt_yuv_i420_to_nv12$address() {
        return cobalt_yuv_i420_to_nv12.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_to_nv12(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstUv, int32_t dstStrideUv, int32_t width, int32_t height)
     * }
     */
    public static int cobalt_yuv_i420_to_nv12(MemorySegment srcY, int srcStrideY, MemorySegment srcU, int srcStrideU, MemorySegment srcV, int srcStrideV, MemorySegment dstY, int dstStrideY, MemorySegment dstUv, int dstStrideUv, int width, int height) {
        var mh$ = cobalt_yuv_i420_to_nv12.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_i420_to_nv12", srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstY, dstStrideY, dstUv, dstStrideUv, width, height);
            }
            return (int)mh$.invokeExact(srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstY, dstStrideY, dstUv, dstStrideUv, width, height);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_yuv_i420_scale {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_i420_scale");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_scale(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, int32_t srcWidth, int32_t srcHeight, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t dstWidth, int32_t dstHeight, int32_t filter)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_i420_scale$descriptor() {
        return cobalt_yuv_i420_scale.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_scale(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, int32_t srcWidth, int32_t srcHeight, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t dstWidth, int32_t dstHeight, int32_t filter)
     * }
     */
    public static MethodHandle cobalt_yuv_i420_scale$handle() {
        return cobalt_yuv_i420_scale.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_scale(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, int32_t srcWidth, int32_t srcHeight, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t dstWidth, int32_t dstHeight, int32_t filter)
     * }
     */
    public static MemorySegment cobalt_yuv_i420_scale$address() {
        return cobalt_yuv_i420_scale.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_scale(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, int32_t srcWidth, int32_t srcHeight, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t dstWidth, int32_t dstHeight, int32_t filter)
     * }
     */
    public static int cobalt_yuv_i420_scale(MemorySegment srcY, int srcStrideY, MemorySegment srcU, int srcStrideU, MemorySegment srcV, int srcStrideV, int srcWidth, int srcHeight, MemorySegment dstY, int dstStrideY, MemorySegment dstU, int dstStrideU, MemorySegment dstV, int dstStrideV, int dstWidth, int dstHeight, int filter) {
        var mh$ = cobalt_yuv_i420_scale.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_i420_scale", srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, srcWidth, srcHeight, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, dstWidth, dstHeight, filter);
            }
            return (int)mh$.invokeExact(srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, srcWidth, srcHeight, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, dstWidth, dstHeight, filter);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_yuv_i420_rotate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_POINTER,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT,
            CobaltYuv.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_yuv_i420_rotate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_rotate(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height, int32_t mode)
     * }
     */
    public static FunctionDescriptor cobalt_yuv_i420_rotate$descriptor() {
        return cobalt_yuv_i420_rotate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_rotate(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height, int32_t mode)
     * }
     */
    public static MethodHandle cobalt_yuv_i420_rotate$handle() {
        return cobalt_yuv_i420_rotate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_rotate(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height, int32_t mode)
     * }
     */
    public static MemorySegment cobalt_yuv_i420_rotate$address() {
        return cobalt_yuv_i420_rotate.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_yuv_i420_rotate(const uint8_t *srcY, int32_t srcStrideY, const uint8_t *srcU, int32_t srcStrideU, const uint8_t *srcV, int32_t srcStrideV, uint8_t *dstY, int32_t dstStrideY, uint8_t *dstU, int32_t dstStrideU, uint8_t *dstV, int32_t dstStrideV, int32_t width, int32_t height, int32_t mode)
     * }
     */
    public static int cobalt_yuv_i420_rotate(MemorySegment srcY, int srcStrideY, MemorySegment srcU, int srcStrideU, MemorySegment srcV, int srcStrideV, MemorySegment dstY, int dstStrideY, MemorySegment dstU, int dstStrideU, MemorySegment dstV, int dstStrideV, int width, int height, int mode) {
        var mh$ = cobalt_yuv_i420_rotate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_yuv_i420_rotate", srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height, mode);
            }
            return (int)mh$.invokeExact(srcY, srcStrideY, srcU, srcStrideU, srcV, srcStrideV, dstY, dstStrideY, dstU, dstStrideU, dstV, dstStrideV, width, height, mode);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int COBALT_YUV_ERROR = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_YUV_ERROR -1
     * }
     */
    public static int COBALT_YUV_ERROR() {
        return COBALT_YUV_ERROR;
    }
}

