// Generated by jextract

package com.github.auties00.cobalt.calls2.net.transport.sctp.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class CobaltSctp extends CobaltSctp$shared {

    CobaltSctp() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int COBALT_SCTP_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_OK 0
     * }
     */
    public static int COBALT_SCTP_OK() {
        return COBALT_SCTP_OK;
    }
    private static final int COBALT_SCTP_IN_PROGRESS = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_IN_PROGRESS 1
     * }
     */
    public static int COBALT_SCTP_IN_PROGRESS() {
        return COBALT_SCTP_IN_PROGRESS;
    }
    private static final int COBALT_SCTP_PR_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_PR_NONE 0
     * }
     */
    public static int COBALT_SCTP_PR_NONE() {
        return COBALT_SCTP_PR_NONE;
    }
    private static final int COBALT_SCTP_PR_TTL = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_PR_TTL 1
     * }
     */
    public static int COBALT_SCTP_PR_TTL() {
        return COBALT_SCTP_PR_TTL;
    }
    private static final int COBALT_SCTP_PR_RTX = (int)2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_PR_RTX 2
     * }
     */
    public static int COBALT_SCTP_PR_RTX() {
        return COBALT_SCTP_PR_RTX;
    }

    private static class cobalt_sctp_global_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_global_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_global_init(int32_t port, void *connOutputCb)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_global_init$descriptor() {
        return cobalt_sctp_global_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_global_init(int32_t port, void *connOutputCb)
     * }
     */
    public static MethodHandle cobalt_sctp_global_init$handle() {
        return cobalt_sctp_global_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_global_init(int32_t port, void *connOutputCb)
     * }
     */
    public static MemorySegment cobalt_sctp_global_init$address() {
        return cobalt_sctp_global_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_global_init(int32_t port, void *connOutputCb)
     * }
     */
    public static int cobalt_sctp_global_init(int port, MemorySegment connOutputCb) {
        var mh$ = cobalt_sctp_global_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_global_init", port, connOutputCb);
            }
            return (int)mh$.invokeExact(port, connOutputCb);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_register_address {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_register_address");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_register_address(void *connId)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_register_address$descriptor() {
        return cobalt_sctp_register_address.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_register_address(void *connId)
     * }
     */
    public static MethodHandle cobalt_sctp_register_address$handle() {
        return cobalt_sctp_register_address.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_register_address(void *connId)
     * }
     */
    public static MemorySegment cobalt_sctp_register_address$address() {
        return cobalt_sctp_register_address.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_register_address(void *connId)
     * }
     */
    public static int cobalt_sctp_register_address(MemorySegment connId) {
        var mh$ = cobalt_sctp_register_address.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_register_address", connId);
            }
            return (int)mh$.invokeExact(connId);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_deregister_address {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_deregister_address");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_deregister_address(void *connId)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_deregister_address$descriptor() {
        return cobalt_sctp_deregister_address.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_deregister_address(void *connId)
     * }
     */
    public static MethodHandle cobalt_sctp_deregister_address$handle() {
        return cobalt_sctp_deregister_address.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_deregister_address(void *connId)
     * }
     */
    public static MemorySegment cobalt_sctp_deregister_address$address() {
        return cobalt_sctp_deregister_address.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_deregister_address(void *connId)
     * }
     */
    public static int cobalt_sctp_deregister_address(MemorySegment connId) {
        var mh$ = cobalt_sctp_deregister_address.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_deregister_address", connId);
            }
            return (int)mh$.invokeExact(connId);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_handle_timers {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_handle_timers");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_handle_timers(int32_t elapsedMs)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_handle_timers$descriptor() {
        return cobalt_sctp_handle_timers.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_handle_timers(int32_t elapsedMs)
     * }
     */
    public static MethodHandle cobalt_sctp_handle_timers$handle() {
        return cobalt_sctp_handle_timers.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_handle_timers(int32_t elapsedMs)
     * }
     */
    public static MemorySegment cobalt_sctp_handle_timers$address() {
        return cobalt_sctp_handle_timers.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_handle_timers(int32_t elapsedMs)
     * }
     */
    public static int cobalt_sctp_handle_timers(int elapsedMs) {
        var mh$ = cobalt_sctp_handle_timers.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_handle_timers", elapsedMs);
            }
            return (int)mh$.invokeExact(elapsedMs);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_socket_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_socket_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_socket_create(void *receiveCb, void *ulpInfo, void **outSock)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_socket_create$descriptor() {
        return cobalt_sctp_socket_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_socket_create(void *receiveCb, void *ulpInfo, void **outSock)
     * }
     */
    public static MethodHandle cobalt_sctp_socket_create$handle() {
        return cobalt_sctp_socket_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_socket_create(void *receiveCb, void *ulpInfo, void **outSock)
     * }
     */
    public static MemorySegment cobalt_sctp_socket_create$address() {
        return cobalt_sctp_socket_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_socket_create(void *receiveCb, void *ulpInfo, void **outSock)
     * }
     */
    public static int cobalt_sctp_socket_create(MemorySegment receiveCb, MemorySegment ulpInfo, MemorySegment outSock) {
        var mh$ = cobalt_sctp_socket_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_socket_create", receiveCb, ulpInfo, outSock);
            }
            return (int)mh$.invokeExact(receiveCb, ulpInfo, outSock);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_bind {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_bind");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_bind(void *sock, int32_t port, void *connId)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_bind$descriptor() {
        return cobalt_sctp_bind.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_bind(void *sock, int32_t port, void *connId)
     * }
     */
    public static MethodHandle cobalt_sctp_bind$handle() {
        return cobalt_sctp_bind.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_bind(void *sock, int32_t port, void *connId)
     * }
     */
    public static MemorySegment cobalt_sctp_bind$address() {
        return cobalt_sctp_bind.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_bind(void *sock, int32_t port, void *connId)
     * }
     */
    public static int cobalt_sctp_bind(MemorySegment sock, int port, MemorySegment connId) {
        var mh$ = cobalt_sctp_bind.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_bind", sock, port, connId);
            }
            return (int)mh$.invokeExact(sock, port, connId);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_connect {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_connect");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_connect(void *sock, int32_t port, void *connId)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_connect$descriptor() {
        return cobalt_sctp_connect.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_connect(void *sock, int32_t port, void *connId)
     * }
     */
    public static MethodHandle cobalt_sctp_connect$handle() {
        return cobalt_sctp_connect.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_connect(void *sock, int32_t port, void *connId)
     * }
     */
    public static MemorySegment cobalt_sctp_connect$address() {
        return cobalt_sctp_connect.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_connect(void *sock, int32_t port, void *connId)
     * }
     */
    public static int cobalt_sctp_connect(MemorySegment sock, int port, MemorySegment connId) {
        var mh$ = cobalt_sctp_connect.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_connect", sock, port, connId);
            }
            return (int)mh$.invokeExact(sock, port, connId);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_conninput {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_conninput");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_conninput(void *connId, const uint8_t *data, size_t len)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_conninput$descriptor() {
        return cobalt_sctp_conninput.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_conninput(void *connId, const uint8_t *data, size_t len)
     * }
     */
    public static MethodHandle cobalt_sctp_conninput$handle() {
        return cobalt_sctp_conninput.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_conninput(void *connId, const uint8_t *data, size_t len)
     * }
     */
    public static MemorySegment cobalt_sctp_conninput$address() {
        return cobalt_sctp_conninput.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_conninput(void *connId, const uint8_t *data, size_t len)
     * }
     */
    public static int cobalt_sctp_conninput(MemorySegment connId, MemorySegment data, long len) {
        var mh$ = cobalt_sctp_conninput.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_conninput", connId, data, len);
            }
            return (int)mh$.invokeExact(connId, data, len);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_send {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_LONG_LONG,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_LONG_LONG,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_send");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_send$descriptor() {
        return cobalt_sctp_send.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered)
     * }
     */
    public static MethodHandle cobalt_sctp_send$handle() {
        return cobalt_sctp_send.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered)
     * }
     */
    public static MemorySegment cobalt_sctp_send$address() {
        return cobalt_sctp_send.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered)
     * }
     */
    public static long cobalt_sctp_send(MemorySegment sock, MemorySegment data, long len, int streamId, int ppid, int unordered) {
        var mh$ = cobalt_sctp_send.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_send", sock, data, len, streamId, ppid, unordered);
            }
            return (long)mh$.invokeExact(sock, data, len, streamId, ppid, unordered);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_send_pr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_LONG_LONG,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_LONG_LONG,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_send_pr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send_pr(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered, int32_t prPolicy, int32_t prValue)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_send_pr$descriptor() {
        return cobalt_sctp_send_pr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send_pr(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered, int32_t prPolicy, int32_t prValue)
     * }
     */
    public static MethodHandle cobalt_sctp_send_pr$handle() {
        return cobalt_sctp_send_pr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send_pr(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered, int32_t prPolicy, int32_t prValue)
     * }
     */
    public static MemorySegment cobalt_sctp_send_pr$address() {
        return cobalt_sctp_send_pr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int64_t cobalt_sctp_send_pr(void *sock, const uint8_t *data, size_t len, int32_t streamId, int32_t ppid, int32_t unordered, int32_t prPolicy, int32_t prValue)
     * }
     */
    public static long cobalt_sctp_send_pr(MemorySegment sock, MemorySegment data, long len, int streamId, int ppid, int unordered, int prPolicy, int prValue) {
        var mh$ = cobalt_sctp_send_pr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_send_pr", sock, data, len, streamId, ppid, unordered, prPolicy, prValue);
            }
            return (long)mh$.invokeExact(sock, data, len, streamId, ppid, unordered, prPolicy, prValue);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_set_nodelay {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_set_nodelay");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_nodelay(void *sock, int32_t on)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_set_nodelay$descriptor() {
        return cobalt_sctp_set_nodelay.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_nodelay(void *sock, int32_t on)
     * }
     */
    public static MethodHandle cobalt_sctp_set_nodelay$handle() {
        return cobalt_sctp_set_nodelay.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_nodelay(void *sock, int32_t on)
     * }
     */
    public static MemorySegment cobalt_sctp_set_nodelay$address() {
        return cobalt_sctp_set_nodelay.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_nodelay(void *sock, int32_t on)
     * }
     */
    public static int cobalt_sctp_set_nodelay(MemorySegment sock, int on) {
        var mh$ = cobalt_sctp_set_nodelay.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_set_nodelay", sock, on);
            }
            return (int)mh$.invokeExact(sock, on);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_set_disable_fragments {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_set_disable_fragments");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_disable_fragments(void *sock, int32_t on)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_set_disable_fragments$descriptor() {
        return cobalt_sctp_set_disable_fragments.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_disable_fragments(void *sock, int32_t on)
     * }
     */
    public static MethodHandle cobalt_sctp_set_disable_fragments$handle() {
        return cobalt_sctp_set_disable_fragments.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_disable_fragments(void *sock, int32_t on)
     * }
     */
    public static MemorySegment cobalt_sctp_set_disable_fragments$address() {
        return cobalt_sctp_set_disable_fragments.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_disable_fragments(void *sock, int32_t on)
     * }
     */
    public static int cobalt_sctp_set_disable_fragments(MemorySegment sock, int on) {
        var mh$ = cobalt_sctp_set_disable_fragments.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_set_disable_fragments", sock, on);
            }
            return (int)mh$.invokeExact(sock, on);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_set_initmsg {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_set_initmsg");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_initmsg(void *sock, int32_t numOstreams, int32_t maxInstreams, int32_t maxAttempts, int32_t maxInitTimeo)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_set_initmsg$descriptor() {
        return cobalt_sctp_set_initmsg.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_initmsg(void *sock, int32_t numOstreams, int32_t maxInstreams, int32_t maxAttempts, int32_t maxInitTimeo)
     * }
     */
    public static MethodHandle cobalt_sctp_set_initmsg$handle() {
        return cobalt_sctp_set_initmsg.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_initmsg(void *sock, int32_t numOstreams, int32_t maxInstreams, int32_t maxAttempts, int32_t maxInitTimeo)
     * }
     */
    public static MemorySegment cobalt_sctp_set_initmsg$address() {
        return cobalt_sctp_set_initmsg.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_initmsg(void *sock, int32_t numOstreams, int32_t maxInstreams, int32_t maxAttempts, int32_t maxInitTimeo)
     * }
     */
    public static int cobalt_sctp_set_initmsg(MemorySegment sock, int numOstreams, int maxInstreams, int maxAttempts, int maxInitTimeo) {
        var mh$ = cobalt_sctp_set_initmsg.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_set_initmsg", sock, numOstreams, maxInstreams, maxAttempts, maxInitTimeo);
            }
            return (int)mh$.invokeExact(sock, numOstreams, maxInstreams, maxAttempts, maxInitTimeo);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_subscribe_assoc_change {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_subscribe_assoc_change");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_subscribe_assoc_change(void *sock, int32_t on)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_subscribe_assoc_change$descriptor() {
        return cobalt_sctp_subscribe_assoc_change.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_subscribe_assoc_change(void *sock, int32_t on)
     * }
     */
    public static MethodHandle cobalt_sctp_subscribe_assoc_change$handle() {
        return cobalt_sctp_subscribe_assoc_change.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_subscribe_assoc_change(void *sock, int32_t on)
     * }
     */
    public static MemorySegment cobalt_sctp_subscribe_assoc_change$address() {
        return cobalt_sctp_subscribe_assoc_change.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_subscribe_assoc_change(void *sock, int32_t on)
     * }
     */
    public static int cobalt_sctp_subscribe_assoc_change(MemorySegment sock, int on) {
        var mh$ = cobalt_sctp_subscribe_assoc_change.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_subscribe_assoc_change", sock, on);
            }
            return (int)mh$.invokeExact(sock, on);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_set_non_blocking {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER,
            CobaltSctp.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_set_non_blocking");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_non_blocking(void *sock, int32_t on)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_set_non_blocking$descriptor() {
        return cobalt_sctp_set_non_blocking.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_non_blocking(void *sock, int32_t on)
     * }
     */
    public static MethodHandle cobalt_sctp_set_non_blocking$handle() {
        return cobalt_sctp_set_non_blocking.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_non_blocking(void *sock, int32_t on)
     * }
     */
    public static MemorySegment cobalt_sctp_set_non_blocking$address() {
        return cobalt_sctp_set_non_blocking.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_set_non_blocking(void *sock, int32_t on)
     * }
     */
    public static int cobalt_sctp_set_non_blocking(MemorySegment sock, int on) {
        var mh$ = cobalt_sctp_set_non_blocking.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_set_non_blocking", sock, on);
            }
            return (int)mh$.invokeExact(sock, on);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_sctp_close {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltSctp.C_INT,
            CobaltSctp.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cobalt_sctp_close");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_close(void *sock)
     * }
     */
    public static FunctionDescriptor cobalt_sctp_close$descriptor() {
        return cobalt_sctp_close.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_close(void *sock)
     * }
     */
    public static MethodHandle cobalt_sctp_close$handle() {
        return cobalt_sctp_close.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_sctp_close(void *sock)
     * }
     */
    public static MemorySegment cobalt_sctp_close$address() {
        return cobalt_sctp_close.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_sctp_close(void *sock)
     * }
     */
    public static int cobalt_sctp_close(MemorySegment sock) {
        var mh$ = cobalt_sctp_close.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_sctp_close", sock);
            }
            return (int)mh$.invokeExact(sock);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int COBALT_SCTP_BAD_PARAM = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_BAD_PARAM -1
     * }
     */
    public static int COBALT_SCTP_BAD_PARAM() {
        return COBALT_SCTP_BAD_PARAM;
    }
    private static final int COBALT_SCTP_NOMEM = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_NOMEM -2
     * }
     */
    public static int COBALT_SCTP_NOMEM() {
        return COBALT_SCTP_NOMEM;
    }
    private static final int COBALT_SCTP_FAIL = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_SCTP_FAIL -3
     * }
     */
    public static int COBALT_SCTP_FAIL() {
        return COBALT_SCTP_FAIL;
    }
}

