// Generated by jextract

package com.github.auties00.cobalt.net.bindings.macos;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;

public class SCReachability {

    SCReachability() {
        // Should not be called directly
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static class SCNetworkReachabilityCreateWithAddress {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SCNetworkReachabilityCreateWithAddress");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * SCNetworkReachabilityRef SCNetworkReachabilityCreateWithAddress(CFAllocatorRef allocator, const struct sockaddr *address)
     * }
     */
    public static MethodHandle SCNetworkReachabilityCreateWithAddress$handle() {
        return SCNetworkReachabilityCreateWithAddress.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * SCNetworkReachabilityRef SCNetworkReachabilityCreateWithAddress(CFAllocatorRef allocator, const struct sockaddr *address)
     * }
     */
    public static MemorySegment SCNetworkReachabilityCreateWithAddress(MemorySegment allocator, MemorySegment address) {
        try {
            return (MemorySegment) SCNetworkReachabilityCreateWithAddress.HANDLE.invokeExact(allocator, address);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SCNetworkReachabilityGetFlags {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_BYTE, ADDRESS, ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SCNetworkReachabilityGetFlags");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityGetFlags(SCNetworkReachabilityRef target, SCNetworkReachabilityFlags *flags)
     * }
     */
    public static MethodHandle SCNetworkReachabilityGetFlags$handle() {
        return SCNetworkReachabilityGetFlags.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityGetFlags(SCNetworkReachabilityRef target, SCNetworkReachabilityFlags *flags)
     * }
     */
    public static byte SCNetworkReachabilityGetFlags(MemorySegment target, MemorySegment flags) {
        try {
            return (byte) SCNetworkReachabilityGetFlags.HANDLE.invokeExact(target, flags);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class CFRelease {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("CFRelease");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * void CFRelease(CFTypeRef cf)
     * }
     */
    public static MethodHandle CFRelease$handle() {
        return CFRelease.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * void CFRelease(CFTypeRef cf)
     * }
     */
    public static void CFRelease(MemorySegment cf) {
        try {
            CFRelease.HANDLE.invokeExact(cf);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SCNetworkReachabilitySetCallback {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_BYTE, ADDRESS, ADDRESS, ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SCNetworkReachabilitySetCallback");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilitySetCallback(SCNetworkReachabilityRef target, SCNetworkReachabilityCallBack callout, SCNetworkReachabilityContext *context)
     * }
     */
    public static MethodHandle SCNetworkReachabilitySetCallback$handle() {
        return SCNetworkReachabilitySetCallback.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilitySetCallback(SCNetworkReachabilityRef target, SCNetworkReachabilityCallBack callout, SCNetworkReachabilityContext *context)
     * }
     */
    public static byte SCNetworkReachabilitySetCallback(MemorySegment target, MemorySegment callout, MemorySegment context) {
        try {
            return (byte) SCNetworkReachabilitySetCallback.HANDLE.invokeExact(target, callout, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SCNetworkReachabilityScheduleWithRunLoop {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_BYTE, ADDRESS, ADDRESS, ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SCNetworkReachabilityScheduleWithRunLoop");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityScheduleWithRunLoop(SCNetworkReachabilityRef target, CFRunLoopRef runLoop, CFStringRef runLoopMode)
     * }
     */
    public static MethodHandle SCNetworkReachabilityScheduleWithRunLoop$handle() {
        return SCNetworkReachabilityScheduleWithRunLoop.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityScheduleWithRunLoop(SCNetworkReachabilityRef target, CFRunLoopRef runLoop, CFStringRef runLoopMode)
     * }
     */
    public static byte SCNetworkReachabilityScheduleWithRunLoop(MemorySegment target, MemorySegment runLoop, MemorySegment runLoopMode) {
        try {
            return (byte) SCNetworkReachabilityScheduleWithRunLoop.HANDLE.invokeExact(target, runLoop, runLoopMode);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SCNetworkReachabilityUnscheduleFromRunLoop {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_BYTE, ADDRESS, ADDRESS, ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SCNetworkReachabilityUnscheduleFromRunLoop");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityUnscheduleFromRunLoop(SCNetworkReachabilityRef target, CFRunLoopRef runLoop, CFStringRef runLoopMode)
     * }
     */
    public static MethodHandle SCNetworkReachabilityUnscheduleFromRunLoop$handle() {
        return SCNetworkReachabilityUnscheduleFromRunLoop.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * Boolean SCNetworkReachabilityUnscheduleFromRunLoop(SCNetworkReachabilityRef target, CFRunLoopRef runLoop, CFStringRef runLoopMode)
     * }
     */
    public static byte SCNetworkReachabilityUnscheduleFromRunLoop(MemorySegment target, MemorySegment runLoop, MemorySegment runLoopMode) {
        try {
            return (byte) SCNetworkReachabilityUnscheduleFromRunLoop.HANDLE.invokeExact(target, runLoop, runLoopMode);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class CFRunLoopGetCurrent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("CFRunLoopGetCurrent");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * CFRunLoopRef CFRunLoopGetCurrent(void)
     * }
     */
    public static MethodHandle CFRunLoopGetCurrent$handle() {
        return CFRunLoopGetCurrent.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * CFRunLoopRef CFRunLoopGetCurrent(void)
     * }
     */
    public static MemorySegment CFRunLoopGetCurrent() {
        try {
            return (MemorySegment) CFRunLoopGetCurrent.HANDLE.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class CFRunLoopRun {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid();
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("CFRunLoopRun");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * void CFRunLoopRun(void)
     * }
     */
    public static MethodHandle CFRunLoopRun$handle() {
        return CFRunLoopRun.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * void CFRunLoopRun(void)
     * }
     */
    public static void CFRunLoopRun() {
        try {
            CFRunLoopRun.HANDLE.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class CFRunLoopStop {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ADDRESS);
        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("CFRunLoopStop");
        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * {@snippet lang=c :
     * void CFRunLoopStop(CFRunLoopRef rl)
     * }
     */
    public static MethodHandle CFRunLoopStop$handle() {
        return CFRunLoopStop.HANDLE;
    }

    /**
     * {@snippet lang=c :
     * void CFRunLoopStop(CFRunLoopRef rl)
     * }
     */
    public static void CFRunLoopStop(MemorySegment rl) {
        try {
            CFRunLoopStop.HANDLE.invokeExact(rl);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class kCFRunLoopDefaultMode {
        public static final MemorySegment SEGMENT = SYMBOL_LOOKUP.findOrThrow("kCFRunLoopDefaultMode")
                .reinterpret(ADDRESS.byteSize());
    }

    /**
     * {@snippet lang=c :
     * extern const CFStringRef kCFRunLoopDefaultMode
     * }
     */
    public static MemorySegment kCFRunLoopDefaultMode() {
        return kCFRunLoopDefaultMode.SEGMENT.get(ADDRESS, 0);
    }
}
