// Generated by jextract

package com.github.auties00.cobalt.net.bindings.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Iphlpapi extends Iphlpapi$shared {

    Iphlpapi() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class NotifyAddrChange {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Iphlpapi.C_LONG,
            Iphlpapi.C_POINTER,
            Iphlpapi.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("NotifyAddrChange");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * DWORD NotifyAddrChange(PHANDLE Handle, LPOVERLAPPED overlapped)
     * }
     */
    public static FunctionDescriptor NotifyAddrChange$descriptor() {
        return NotifyAddrChange.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * DWORD NotifyAddrChange(PHANDLE Handle, LPOVERLAPPED overlapped)
     * }
     */
    public static MethodHandle NotifyAddrChange$handle() {
        return NotifyAddrChange.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * DWORD NotifyAddrChange(PHANDLE Handle, LPOVERLAPPED overlapped)
     * }
     */
    public static MemorySegment NotifyAddrChange$address() {
        return NotifyAddrChange.ADDR;
    }

    /**
     * {@snippet lang=c :
     * DWORD NotifyAddrChange(PHANDLE Handle, LPOVERLAPPED overlapped)
     * }
     */
    public static int NotifyAddrChange(MemorySegment Handle, MemorySegment overlapped) {
        var mh$ = NotifyAddrChange.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("NotifyAddrChange", Handle, overlapped);
            }
            return (int)mh$.invokeExact(Handle, overlapped);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetNetworkConnectivityHint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Iphlpapi.C_LONG,
            Iphlpapi.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("GetNetworkConnectivityHint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * DWORD GetNetworkConnectivityHint(NL_NETWORK_CONNECTIVITY_HINT *ConnectivityHint)
     * }
     */
    public static FunctionDescriptor GetNetworkConnectivityHint$descriptor() {
        return GetNetworkConnectivityHint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * DWORD GetNetworkConnectivityHint(NL_NETWORK_CONNECTIVITY_HINT *ConnectivityHint)
     * }
     */
    public static MethodHandle GetNetworkConnectivityHint$handle() {
        return GetNetworkConnectivityHint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * DWORD GetNetworkConnectivityHint(NL_NETWORK_CONNECTIVITY_HINT *ConnectivityHint)
     * }
     */
    public static MemorySegment GetNetworkConnectivityHint$address() {
        return GetNetworkConnectivityHint.ADDR;
    }

    /**
     * {@snippet lang=c :
     * DWORD GetNetworkConnectivityHint(NL_NETWORK_CONNECTIVITY_HINT *ConnectivityHint)
     * }
     */
    public static int GetNetworkConnectivityHint(MemorySegment ConnectivityHint) {
        var mh$ = GetNetworkConnectivityHint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetNetworkConnectivityHint", ConnectivityHint);
            }
            return (int)mh$.invokeExact(ConnectivityHint);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

