package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Creates an appeal against an enforcement decision previously taken by
 * WhatsApp on a report (for example a ban or content removal) and returns
 * the resulting appeal record.
 *
 * <p>This mutation is issued from the "appeal decision" flow surfaced to
 * newsletter admins and channel owners. The response carries the full appeal
 * state (report id, status, timestamps, channel metadata and the associated
 * server message ids) so the client can render the appeal timeline
 * immediately after submission.
 *
 * <p>This type is generated by the mex-codegen tool from the corresponding WA
 * Web GraphQL mutation. Manual edits will be overwritten on the next
 * generation run.
 */
@WhatsAppWebModule(moduleName = "WAWebMexCreateReportAppealJob")
public final class CreateReportAppealMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexCreateReportAppealJobMutation} GraphQL operation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "27283301737925761";

    /**
     * The GraphQL operation name reported by WA Web's {@code MexPerfTracker}
     * when dispatching this query, mirroring the {@code params.name} value of
     * the compiled {@code createReportAppeal} operation.
     */
    public static final String OPERATION_NAME = "createReportAppeal";
    /**
     * The free-form justification bound to the {@code reason} GraphQL variable.
     */
    private final String reason;
    /**
     * The identifier of the report being contested, bound to the
     * {@code report_id} GraphQL variable.
     */
    private final String reportId;

    /**
     * Constructs a request carrying the appeal {@code reason} and
     * {@code report_id} GraphQL variables.
     *
     * @param reason   the free-form justification for the appeal
     * @param reportId the identifier of the report being contested
     */
    public CreateReportAppealMexRequest(String reason, String reportId) {
        this.reason = reason;
        this.reportId = reportId;
    }

    /**
     * Returns the compiled GraphQL query identifier.
     *
     * @return the constant {@link #QUERY_ID}; never {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name.
     *
     * @return the constant {@link #OPERATION_NAME}; never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJob", exports = "createReportAppeal",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            if (reason != null) {
                writer.writeName("reason");
                writer.writeColon();
                writer.writeString(reason);
            }
            if (reportId != null) {
                writer.writeName("report_id");
                writer.writeColon();
                writer.writeString(reportId);
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
