package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import com.alibaba.fastjson2.JSONObject;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Parsed response of the {@link CreateReportAppealMexRequest} mutation,
 * exposing the resulting appeal record returned by the relay.
 *
 * <p>This type is generated by the mex-codegen tool. Manual edits will be
 * overwritten on the next generation run.
 */
@WhatsAppWebModule(moduleName = "WAWebMexCreateReportAppealJob")
public final class CreateReportAppealMexResponse implements MexOperation.Response.Json {
    /**
     * The {@code report_id} scalar identifying the appealed report.
     */
    private final String reportId;
    /**
     * The {@code status} scalar reflecting the report state.
     */
    private final String status;
    /**
     * The {@code creation_time} scalar (Unix epoch second).
     */
    private final Long creationTime;
    /**
     * The {@code last_update_time} scalar (Unix epoch second).
     */
    private final Long lastUpdateTime;
    /**
     * The {@code channel_name} scalar.
     */
    private final String channelName;
    /**
     * The {@code channel_jid} scalar.
     */
    private final String channelJid;
    /**
     * The {@code server_msg_id} scalar nested under
     * {@code reported_content_data}.
     */
    private final String serverMsgId;
    /**
     * The {@code server_response_id} scalar nested under
     * {@code reported_content_data}.
     */
    private final String responseServerMsgId;
    /**
     * The {@code notify_name} scalar nested under
     * {@code reported_content_data}.
     */
    private final String notifyName;
    /**
     * The parsed {@code appeal} sub-object.
     */
    private final Appeal appeal;

    /**
     * Constructs a response wrapping the parsed scalar and nested fields of
     * the {@code xwa2_create_channel_report_appeal_v2} envelope.
     *
     * @param reportId             the {@code report_id} scalar
     * @param status               the {@code status} scalar
     * @param creationTime         the {@code creation_time} scalar
     * @param lastUpdateTime       the {@code last_update_time} scalar
     * @param channelName          the {@code channel_name} scalar
     * @param channelJid           the {@code channel_jid} scalar
     * @param serverMsgId          the {@code server_msg_id} scalar
     * @param responseServerMsgId  the {@code server_response_id} scalar
     * @param notifyName           the {@code notify_name} scalar
     * @param appeal               the parsed {@code appeal} sub-object
     */
    private CreateReportAppealMexResponse(String reportId, String status, Long creationTime, Long lastUpdateTime, String channelName, String channelJid, String serverMsgId, String responseServerMsgId, String notifyName, Appeal appeal) {
        this.reportId = reportId;
        this.status = status;
        this.creationTime = creationTime;
        this.lastUpdateTime = lastUpdateTime;
        this.channelName = channelName;
        this.channelJid = channelJid;
        this.serverMsgId = serverMsgId;
        this.responseServerMsgId = responseServerMsgId;
        this.notifyName = notifyName;
        this.appeal = appeal;
    }

    /**
     * Parses the MEX response carried by an inbound IQ stanza.
     *
     * @implNote Reads the {@code data.xwa2_create_channel_report_appeal_v2}
     * payload (an {@code XWA2ChannelsReport}) including the appeal record and
     * nested {@code reported_content_data} channel metadata.
     * @param node the inbound IQ stanza carrying the {@code <result>} child
     * @return the parsed response, or {@code Optional.empty()} if the
     *         expected JSON shape is absent
     */
    @WhatsAppWebExport(moduleName = "WAWebMexCreateReportAppealJob", exports = "createReportAppeal",
            adaptation = WhatsAppAdaptation.ADAPTED)
    public static Optional<CreateReportAppealMexResponse> of(Node node) {
        return node.getChild("result")
                .flatMap(Node::toContentBytes)
                .flatMap(CreateReportAppealMexResponse::of);
    }

    /**
     * Returns the {@code report_id} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> reportId() {
        return Optional.ofNullable(reportId);
    }

    /**
     * Returns the {@code status} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> status() {
        return Optional.ofNullable(status);
    }

    /**
     * Returns the {@code creation_time} field.
     *
     * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
     */
    public Optional<Instant> creationTime() {
        return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
    }

    /**
     * Returns the {@code last_update_time} field.
     *
     * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
     */
    public Optional<Instant> lastUpdateTime() {
        return Optional.ofNullable(lastUpdateTime).map(Instant::ofEpochSecond);
    }

    /**
     * Returns the {@code channel_name} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> channelName() {
        return Optional.ofNullable(channelName);
    }

    /**
     * Returns the {@code channel_jid} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> channelJid() {
        return Optional.ofNullable(channelJid);
    }

    /**
     * Returns the {@code server_msg_id} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> serverMsgId() {
        return Optional.ofNullable(serverMsgId);
    }

    /**
     * Returns the {@code response_server_msg_id} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> responseServerMsgId() {
        return Optional.ofNullable(responseServerMsgId);
    }

    /**
     * Returns the {@code notify_name} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> notifyName() {
        return Optional.ofNullable(notifyName);
    }

    /**
     * Returns the {@code appeal} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<Appeal> appeal() {
        return Optional.ofNullable(appeal);
    }

    /**
     * A parsed {@code Appeal} object.
     */
    public static final class Appeal {
        /**
         * The {@code state} scalar of the appeal.
         */
        private final String state;
        /**
         * The {@code appeal_reason} scalar.
         */
        private final String appealReason;
        /**
         * The {@code creation_time} scalar (Unix epoch second).
         */
        private final Long creationTime;
        /**
         * The {@code report_id} scalar identifying the appealed report.
         */
        private final String reportId;
        /**
         * The {@code appeal_id} scalar.
         */
        private final String appealId;

        /**
         * Constructs an appeal record from the parsed scalar fields.
         *
         * @param state         the {@code state} scalar
         * @param appealReason  the {@code appeal_reason} scalar
         * @param creationTime  the {@code creation_time} scalar
         * @param reportId      the {@code report_id} scalar
         * @param appealId      the {@code appeal_id} scalar
         */
        private Appeal(String state, String appealReason, Long creationTime, String reportId, String appealId) {
            this.state = state;
            this.appealReason = appealReason;
            this.creationTime = creationTime;
            this.reportId = reportId;
            this.appealId = appealId;
        }

        /**
         * Returns the {@code state} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> state() {
            return Optional.ofNullable(state);
        }

        /**
         * Returns the {@code appeal_reason} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealReason() {
            return Optional.ofNullable(appealReason);
        }

        /**
         * Returns the {@code creation_time} field.
         *
         * @return an {@link Optional} containing the value as an {@link Instant}, or empty if absent
         */
        public Optional<Instant> creationTime() {
            return Optional.ofNullable(creationTime).map(Instant::ofEpochSecond);
        }

        /**
         * Returns the {@code report_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> reportId() {
            return Optional.ofNullable(reportId);
        }

        /**
         * Returns the {@code appeal_id} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> appealId() {
            return Optional.ofNullable(appealId);
        }

        /**
         * Parses a {@code Appeal} from the given JSON object.
         *
         * @param obj the JSON object to parse
         * @return an {@link Optional} containing the parsed result, or empty if {@code obj} is {@code null}
         */
        static Optional<Appeal> of(JSONObject obj) {
            if (obj == null) {
                return Optional.empty();
            }

            var state = obj.getString("state");
            var appealReason = obj.getString("appeal_reason");
            var creationTime = obj.getLong("creation_time");
            var reportId = obj.getString("report_id");
            var appealId = obj.getString("appeal_id");
            return Optional.of(new Appeal(state, appealReason, creationTime, reportId, appealId));
        }

        /**
         * Parses a list of {@code Appeal} from the given JSON array.
         *
         * @param arr the JSON array to parse
         * @return the list of parsed results, empty if {@code arr} is {@code null}
         */
        static List<Appeal> ofArray(JSONArray arr) {
            if (arr == null) {
                return List.of();
            }

            var result = new ArrayList<Appeal>(arr.size());
            for (var i = 0; i < arr.size(); i++) {
                of(arr.getJSONObject(i)).ifPresent(result::add);
            }
            return result;
        }
    }

    /**
     * Parses the JSON payload carried by the {@code <result>} child into a
     * {@link CreateReportAppealMexResponse}.
     *
     * @param json the UTF-8 encoded JSON payload
     * @return an {@link Optional} containing the parsed response, or empty
     *         if the {@code data.xwa2_create_channel_report_appeal_v2}
     *         envelope is absent
     */
    private static Optional<CreateReportAppealMexResponse> of(byte[] json) {
        var jsonObject = JSON.parseObject(json);
        if (jsonObject == null) {
            return Optional.empty();
        }

        var data = jsonObject.getJSONObject("data");
        if (data == null) {
            return Optional.empty();
        }

        var root = data.getJSONObject("xwa2_create_channel_report_appeal_v2");
        if (root == null) {
            return Optional.empty();
        }

        var reportId = root.getString("report_id");
        var status = root.getString("status");
        var creationTime = root.getLong("creation_time");
        var lastUpdateTime = root.getLong("last_update_time");
        var channelName = root.getString("channel_name");
        var channelJid = root.getString("channel_jid");
        // server_msg_id, server_response_id and notify_name are nested under reported_content_data
        // (XWA2ChannelServerMsgData and XWA2ChannelQuestionResponseData inline fragments).
        var reportedContentData = root.getJSONObject("reported_content_data");
        var serverMsgId = reportedContentData == null ? null : reportedContentData.getString("server_msg_id");
        var responseServerMsgId = reportedContentData == null ? null : reportedContentData.getString("server_response_id");
        var notifyName = reportedContentData == null ? null : reportedContentData.getString("notify_name");
        var appeal = Appeal.of(root.getJSONObject("appeal")).orElse(null);

        return Optional.of(new CreateReportAppealMexResponse(reportId, status, creationTime, lastUpdateTime, channelName, channelJid, serverMsgId, responseServerMsgId, notifyName, appeal));
    }
}
