package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Fetches a rich link preview (title, description, thumbnail) for a URL
 * shared in a newsletter message, with the server acting as a trusted
 * proxy so the preview reveals no information about the recipient.
 *
 * <p>Unlike the regular client-side link preview used in private chats,
 * the newsletter flow delegates link unfurling to the server to preserve
 * reader anonymity: the client never fetches the target URL directly. The
 * response carries the unfurled metadata plus an encrypted media handle
 * ({@code direct_path}, {@code hash}) that can be used to download the
 * preview thumbnail through the standard media pipeline.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql: the compiled
 * GraphQL operation is dispatched through {@code WAWebMexClient.fetchQuery}
 * and returns the {@code xwa2_newsletter_link_preview} payload.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql")
public sealed interface FetchPlaintextLinkPreviewMex extends MexJsonOperation permits FetchPlaintextLinkPreviewMex.Request, FetchPlaintextLinkPreviewMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchPlaintextLinkPreviewJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql:
     * corresponds to the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9101130456653613";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchPlaintextLinkPreviewMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql: the
         * single {@code input} variable carries the serialised URL and
         * optional preview options.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchPlaintextLinkPreviewMex {
        private final String description;
        private final String directPath;
        private final String hash;
        private final String previewType;
        private final String thumbData;
        private final String title;
        private final String height;
        private final String width;

        private Response(String description, String directPath, String hash, String previewType, String thumbData, String title, String height, String width) {
            this.description = description;
            this.directPath = directPath;
            this.hash = hash;
            this.previewType = previewType;
            this.thumbData = thumbData;
            this.title = title;
            this.height = height;
            this.width = width;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql: reads
         * the preview metadata and the encrypted media handle from
         * {@code data.xwa2_newsletter_link_preview}.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code description} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> description() {
            return Optional.ofNullable(description);
        }

        /**
         * Returns the {@code direct_path} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> directPath() {
            return Optional.ofNullable(directPath);
        }

        /**
         * Returns the {@code hash} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> hash() {
            return Optional.ofNullable(hash);
        }

        /**
         * Returns the {@code preview_type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> previewType() {
            return Optional.ofNullable(previewType);
        }

        /**
         * Returns the {@code thumb_data} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> thumbData() {
            return Optional.ofNullable(thumbData);
        }

        /**
         * Returns the {@code title} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> title() {
            return Optional.ofNullable(title);
        }

        /**
         * Returns the {@code height} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> height() {
            return Optional.ofNullable(height);
        }

        /**
         * Returns the {@code width} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> width() {
            return Optional.ofNullable(width);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_newsletter_link_preview");
            if (root == null) {
                return Optional.empty();
            }

            var description = root.getString("description");
            var directPath = root.getString("direct_path");
            var hash = root.getString("hash");
            var previewType = root.getString("preview_type");
            var thumbData = root.getString("thumb_data");
            var title = root.getString("title");
            var height = root.getString("height");
            var width = root.getString("width");

            return Optional.of(new Response(description, directPath, hash, previewType, thumbData, title, height, width));
        }
    }
}
