package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Fetches the current outbound messaging quota enforced on the account by
 * the new-chat messaging capping policy.
 *
 * <p>WhatsApp enforces a sliding-window quota on how many new chats a user
 * can initiate per billing cycle. This query returns the total quota, used
 * quota, cycle start/end timestamps and a series of status flags
 * ({@code oteStatus}, {@code mvStatus}, {@code cappingStatus}) that drive
 * the throttling UI and per-message warnings.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql: the
 * compiled GraphQL operation is dispatched through
 * {@code WAWebMexClient.fetchQuery} and returns the
 * {@code xwa2_fetch_new_chat_message_capping_info} payload.
 */
public final class FetchNewChatMessageCappingInfoMexRequest implements MexOperation.Request.Json {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchNewChatMessageCappingInfoJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql:
     * corresponds to the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    public static final String QUERY_ID = "24503548349331633";

    /**
     * The GraphQL operation name reported by WA Web's
     * {@code MexPerfTracker} when dispatching this query, mirroring the
     * {@code params.name} value of the compiled mexFetchNewChatMessageCapping
     * operation.
     *
     * <p>The constant is exposed through {@link #name()} so
     * call sites can reach the same telemetry tag WA Web emits without
     * duplicating the literal at every dispatch site.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql: WA Web invokes the operation through
     * {@code WAWebMexClient.fetchQuery} which forwards to
     * {@code WAWebMexNativeClient}; the native client passes the
     * {@code params.name} of the compiled GraphQL artifact to
     * {@code MexPerfTracker.setOperationName}. Cobalt mirrors that
     * scalar verbatim as {@code "mexFetchNewChatMessageCapping"}.
     */
    public static final String OPERATION_NAME = "mexFetchNewChatMessageCapping";
    private final String input;

    public FetchNewChatMessageCappingInfoMexRequest(String input) {
        this.input = input;
    }

    /**
     * Returns the compiled GraphQL query identifier projected from
     * {@link #QUERY_ID}.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql: WA Web reads the {@code params.id}
     *           field of the compiled artifact and forwards it to
     *           {@code MexPerfTracker.setQueryId}; Cobalt projects
     *           the same scalar through this accessor.
     * @return the constant {@link #QUERY_ID}; never
     *         {@code null}
     */
    @Override
    public String id() {
        return QUERY_ID;
    }

    /**
     * Returns the GraphQL operation name projected from
     * {@link #OPERATION_NAME}.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql: WA Web's
     *           {@code WAWebMexNativeClient.fetchQuery} reads
     *           {@code params.name} from the compiled GraphQL
     *           artifact and forwards it to
     *           {@code MexPerfTracker.setOperationName}; Cobalt
     *           projects the same scalar through this accessor.
     * @return the constant {@link #OPERATION_NAME};
     *         never {@code null}
     */
    @Override
    public String name() {
        return OPERATION_NAME;
    }

    /**
     * Serialises the GraphQL variables as JSON and wraps them in a
     * {@code w:mex} IQ stanza.
     *
     * @implNote WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql:
     * the single {@code input} variable carries the serialised request
     * options.
     * @return the IQ {@link NodeBuilder} ready to be built and dispatched
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchNewChatMessageCappingInfoJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.ADAPTED)
    @Override
    public NodeBuilder toNode() {
        try (var writer = JSONWriter.ofUTF8()) {
            writer.startObject();
            writer.writeName("variables");
            writer.writeColon();
            writer.startObject();
            if (input != null) {
                writer.writeName("input");
                writer.writeColon();
                writer.writeString(input);
            }
            writer.endObject();
            writer.endObject();
            try (var output = new StringWriter()) {
                writer.flushTo(output);
                return Json.createMexNode(QUERY_ID, output.toString());
            }
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }
}
