package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Fetches the current "reachout timelock" enforcement status for the
 * account, a cooldown window during which outgoing contact attempts are
 * restricted following spam reports or suspicious activity.
 *
 * <p>The response indicates whether the timelock is active, when its
 * enforcement window ends and which enforcement type applies (soft warning,
 * hard block, etc.). The information is surfaced in the send path to
 * suppress or gate new-chat initiation.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL query. Manual edits will be overwritten
 * on the next generation run.
 *
 * @implNote WAWebMexFetchReachoutTimelockJobQuery.graphql: the compiled
 * GraphQL operation is dispatched through {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchReachoutTimelockJobQuery.graphql")
public sealed interface FetchReachoutTimelockMex extends MexJsonOperation permits FetchReachoutTimelockMex.Request, FetchReachoutTimelockMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexFetchReachoutTimelockJobQuery} GraphQL operation.
     *
     * @implNote WAWebMexFetchReachoutTimelockJobQuery.graphql: corresponds
     * to the {@code params.id} field of the compiled query.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchReachoutTimelockJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "23983697327930364";

    /**
     * The request payload for this MEX query.
     */
    final class Request implements FetchReachoutTimelockMex {

        public Request() {
        }

        /**
         * Serialises an empty GraphQL variables envelope and wraps it in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexFetchReachoutTimelockJobQuery.graphql: the query
         * takes no variables and operates on the caller's identity.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchReachoutTimelockJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX query.
     */
    final class Response implements FetchReachoutTimelockMex {
        private final Boolean isActive;
        private final String timeEnforcementEnds;
        private final String enforcementType;

        private Response(Boolean isActive, String timeEnforcementEnds, String enforcementType) {
            this.isActive = isActive;
            this.timeEnforcementEnds = timeEnforcementEnds;
            this.enforcementType = enforcementType;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexFetchReachoutTimelockJobQuery.graphql: reads the
         * {@code is_active}, {@code time_enforcement_ends} and
         * {@code enforcement_type} fields from the response payload.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexFetchReachoutTimelockJobQuery.graphql", exports = "params.id",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code is_active} field.
         *
         * @return {@code true} if the value is present and true, {@code false} otherwise
         */
        public boolean isActive() {
            return isActive != null && isActive;
        }

        /**
         * Returns the {@code time_enforcement_ends} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> timeEnforcementEnds() {
            return Optional.ofNullable(timeEnforcementEnds);
        }

        /**
         * Returns the {@code enforcement_type} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> enforcementType() {
            return Optional.ofNullable(enforcementType);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_fetch_account_reachout_timelock");
            if (root == null) {
                return Optional.empty();
            }

            var isActive = root.getBoolean("is_active");
            var timeEnforcementEnds = root.getString("time_enforcement_ends");
            var enforcementType = root.getString("enforcement_type");

            return Optional.of(new Response(isActive, timeEnforcementEnds, enforcementType));
        }
    }
}
