package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.MexOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Optional;

/**
 * Parsed response of the {@link FetchPlaintextLinkPreviewMexRequest} query,
 * exposing the unfurled link metadata and encrypted thumbnail handle from the
 * {@code xwa2_newsletter_link_preview} envelope.
 *
 * <p>This type is generated by the mex-codegen tool. Manual edits will be
 * overwritten on the next generation run.
 */
@WhatsAppWebModule(moduleName = "WAWebMexFetchPlaintextLinkPreviewJob")
public final class FetchPlaintextLinkPreviewMexResponse implements MexOperation.Response.Json {
    /**
     * The {@code description} scalar.
     */
    private final String description;
    /**
     * The {@code direct_path} scalar carrying the encrypted thumbnail media handle.
     */
    private final String directPath;
    /**
     * The {@code hash} scalar paired with {@link #directPath}.
     */
    private final String hash;
    /**
     * The {@code preview_type} scalar.
     */
    private final String previewType;
    /**
     * The {@code thumb_data} scalar carrying the inline thumbnail bytes.
     */
    private final String thumbData;
    /**
     * The {@code title} scalar.
     */
    private final String title;
    /**
     * The {@code height} scalar of the preview thumbnail.
     */
    private final String height;
    /**
     * The {@code width} scalar of the preview thumbnail.
     */
    private final String width;

    /**
     * Constructs a response wrapping the parsed scalar fields of the
     * {@code xwa2_newsletter_link_preview} envelope.
     *
     * @param description  the {@code description} scalar
     * @param directPath   the {@code direct_path} scalar
     * @param hash         the {@code hash} scalar
     * @param previewType  the {@code preview_type} scalar
     * @param thumbData    the {@code thumb_data} scalar
     * @param title        the {@code title} scalar
     * @param height       the {@code height} scalar
     * @param width        the {@code width} scalar
     */
    private FetchPlaintextLinkPreviewMexResponse(String description, String directPath, String hash, String previewType, String thumbData, String title, String height, String width) {
        this.description = description;
        this.directPath = directPath;
        this.hash = hash;
        this.previewType = previewType;
        this.thumbData = thumbData;
        this.title = title;
        this.height = height;
        this.width = width;
    }

    /**
     * Parses the MEX response carried by an inbound IQ stanza.
     *
     * @param node the inbound IQ stanza carrying the {@code <result>} child
     * @return the parsed response, or {@code Optional.empty()} if the
     *         expected JSON shape is absent
     */
    @WhatsAppWebExport(moduleName = "WAWebMexFetchPlaintextLinkPreviewJobQuery.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.ADAPTED)
    public static Optional<FetchPlaintextLinkPreviewMexResponse> of(Node node) {
        return node.getChild("result")
                .flatMap(Node::toContentBytes)
                .flatMap(FetchPlaintextLinkPreviewMexResponse::of);
    }

    /**
     * Returns the {@code description} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> description() {
        return Optional.ofNullable(description);
    }

    /**
     * Returns the {@code direct_path} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> directPath() {
        return Optional.ofNullable(directPath);
    }

    /**
     * Returns the {@code hash} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> hash() {
        return Optional.ofNullable(hash);
    }

    /**
     * Returns the {@code preview_type} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> previewType() {
        return Optional.ofNullable(previewType);
    }

    /**
     * Returns the {@code thumb_data} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> thumbData() {
        return Optional.ofNullable(thumbData);
    }

    /**
     * Returns the {@code title} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> title() {
        return Optional.ofNullable(title);
    }

    /**
     * Returns the {@code height} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> height() {
        return Optional.ofNullable(height);
    }

    /**
     * Returns the {@code width} field.
     *
     * @return an {@link Optional} containing the value, or empty if absent
     */
    public Optional<String> width() {
        return Optional.ofNullable(width);
    }

    /**
     * Parses the JSON payload carried by the {@code <result>} child into a
     * {@link FetchPlaintextLinkPreviewMexResponse}.
     *
     * @param json the UTF-8 encoded JSON payload
     * @return an {@link Optional} containing the parsed response, or empty
     *         if the {@code data.xwa2_newsletter_link_preview} envelope is absent
     */
    private static Optional<FetchPlaintextLinkPreviewMexResponse> of(byte[] json) {
        var jsonObject = JSON.parseObject(json);
        if (jsonObject == null) {
            return Optional.empty();
        }

        var data = jsonObject.getJSONObject("data");
        if (data == null) {
            return Optional.empty();
        }

        var root = data.getJSONObject("xwa2_newsletter_link_preview");
        if (root == null) {
            return Optional.empty();
        }

        var description = root.getString("description");
        var directPath = root.getString("direct_path");
        var hash = root.getString("hash");
        var previewType = root.getString("preview_type");
        var thumbData = root.getString("thumb_data");
        var title = root.getString("title");
        var height = root.getString("height");
        var width = root.getString("width");

        return Optional.of(new FetchPlaintextLinkPreviewMexResponse(description, directPath, hash, previewType, thumbData, title, height, width));
    }
}
