package com.github.auties00.cobalt.node.mex.json.misc;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONWriter;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.node.mex.json.MexJsonOperation;
import com.github.auties00.cobalt.node.Node;
import com.github.auties00.cobalt.node.NodeBuilder;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Optional;

/**
 * Requests a Data Subject (Download/Deletion) Request Button reference
 * number, used by the privacy "request my info" and "delete my account"
 * flows required under data protection regulations.
 *
 * <p>Despite being a "get" operation this is modelled as a GraphQL
 * mutation on the server because submitting the request has side effects
 * (it kicks off a data export or deletion job). The response carries the
 * generated reference number so the user can check progress.
 *
 * <p>This type is a sealed interface generated by the mex-codegen tool from
 * the corresponding WA Web GraphQL mutation. Manual edits will be
 * overwritten on the next generation run.
 *
 * @implNote WAWebMexGetDsbInfoJob.getDsbInfo: sends
 * {@code WAWebMexGetDsbInfoJobMutation} through
 * {@code WAWebMexClient.fetchQuery}.
 */
@WhatsAppWebModule(moduleName = "WAWebMexGetDsbInfoJob")
@WhatsAppWebModule(moduleName = "WAWebMexGetDsbInfoJobMutation.graphql")
public sealed interface GetDsbInfoMex extends MexJsonOperation permits GetDsbInfoMex.Request, GetDsbInfoMex.Response {
    /**
     * The numeric query identifier assigned to the compiled
     * {@code WAWebMexGetDsbInfoJobMutation} GraphQL operation.
     *
     * @implNote WAWebMexGetDsbInfoJobMutation.graphql: corresponds to the
     * {@code params.id} field of the compiled mutation.
     */
    @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJobMutation.graphql", exports = "params.id",
            adaptation = WhatsAppAdaptation.DIRECT)
    String QUERY_ID = "9982897848413251";

    /**
     * The request payload for this MEX mutation.
     */
    final class Request implements GetDsbInfoMex {
        private final String input;

        public Request(String input) {
            this.input = input;
        }

        /**
         * Serialises the GraphQL variables as JSON and wraps them in a
         * {@code w:mex} IQ stanza.
         *
         * @implNote WAWebMexGetDsbInfoJob.getDsbInfo: the single
         * {@code input} variable carries the serialised request type.
         * @return the IQ {@link NodeBuilder} ready to be built and dispatched
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "getDsbInfo",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public NodeBuilder toNode() {
            try (var writer = JSONWriter.ofUTF8()) {
                writer.startObject();
                writer.writeName("variables");
                writer.writeColon();
                writer.startObject();
                if (input != null) {
                    writer.writeName("input");
                    writer.writeColon();
                    writer.writeString(input);
                }
                writer.endObject();
                writer.endObject();
                try (var output = new StringWriter()) {
                    writer.flushTo(output);
                    return MexJsonOperation.createMexNode(QUERY_ID, output.toString());
                }
            } catch (IOException exception) {
                throw new UncheckedIOException(exception);
            }
        }
    }

    /**
     * The parsed response for this MEX mutation.
     */
    final class Response implements GetDsbInfoMex {
        private final String referenceNumber;

        private Response(String referenceNumber) {
            this.referenceNumber = referenceNumber;
        }

        /**
         * Parses the MEX response carried by an inbound IQ stanza.
         *
         * @implNote WAWebMexGetDsbInfoJob.getDsbInfo: reads the
         * {@code reference_number} assigned to the new data subject request.
         * @param node the inbound IQ stanza carrying the {@code <result>} child
         * @return the parsed response, or {@code Optional.empty()} if the
         *         expected JSON shape is absent
         */
        @WhatsAppWebExport(moduleName = "WAWebMexGetDsbInfoJob", exports = "getDsbInfo",
                adaptation = WhatsAppAdaptation.ADAPTED)
        public static Optional<Response> of(Node node) {
            return node.getChild("result")
                    .flatMap(Node::toContentBytes)
                    .flatMap(Response::of);
        }

        /**
         * Returns the {@code reference_number} field.
         *
         * @return an {@link Optional} containing the value, or empty if absent
         */
        public Optional<String> referenceNumber() {
            return Optional.ofNullable(referenceNumber);
        }

        private static Optional<Response> of(byte[] json) {
            var jsonObject = JSON.parseObject(json);
            if (jsonObject == null) {
                return Optional.empty();
            }

            var data = jsonObject.getJSONObject("data");
            if (data == null) {
                return Optional.empty();
            }

            var root = data.getJSONObject("xwa2_get_dsb_info");
            if (root == null) {
                return Optional.empty();
            }

            var referenceNumber = root.getString("reference_number");

            return Optional.of(new Response(referenceNumber));
        }
    }
}
